import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'en' | 'hi' | 'te';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.savingsLab': 'Savings Lab',
    'nav.theGap': 'The Gap',
    'nav.dimeTracker': 'DIME Tracker',
    'nav.wealthTracker': 'Wealth Tracker',
    'nav.finScore': 'Fin Score',
    'nav.contact': 'Contact',
    'nav.call': 'Call',
    'nav.guidingWealth': 'Guiding Wealth',
    'nav.tools': 'Tools',

    'hero.title': 'Guiding Wealth.',
    'hero.subtitle': 'Guarding Futures.',
    'hero.description': 'Expert financial planning tailored to your life goals. We help you navigate complex financial landscapes with clarity and confidence.',
    'hero.cta.consultation': 'Book a Consultation',
    'hero.cta.tools': 'Explore Tools',
    'hero.stats.clients': 'Happy Clients',
    'hero.stats.experience': 'Year Experience',
    'hero.stats.tools': 'Free Tools',

    'trust.title': 'Certified Expertise',
    'trust.description': 'Our team consists of certified financial professionals dedicated to providing expert advice and strategic guidance. Your future is in qualified hands.',

    'tools.title': 'Financial Freedom Starts Here',
    'tools.description': 'Powerful tools designed to help you plan, protect, and grow your wealth. All tools run privately in your browser.',
    'tools.try': 'Try Now',
    'tools.explore': 'Explore',

    'showcase.savings.tagline': 'Watch Your Money Grow',
    'showcase.savings.desc': 'Visualize compound interest magic with interactive charts. See how small monthly contributions can build massive wealth over time.',
    'showcase.gap.tagline': 'Plan Your Golden Years',
    'showcase.gap.desc': 'Know exactly how much you need to retire comfortably. Accounts for inflation and uses the proven 4% withdrawal rule.',
    'showcase.dime.tagline': 'Protect What Matters',
    'showcase.dime.desc': 'Calculate your true insurance needs across Debt, Income, Mortgage, and Education. Never be underinsured again.',
    'showcase.wealth.tagline': 'Track Every Rupee',
    'showcase.wealth.desc': 'Monitor your income and expenses with beautiful charts. All data stays private in your browser — zero data retention.',
    'showcase.score.tagline': 'Know Your Financial Health',
    'showcase.score.desc': 'Get a comprehensive score from 0-100 measuring your savings, debt management, emergency readiness, and investment habits.',

    'security.title': 'Your Money. Your Data. Your Privacy.',
    'security.desc': 'Built with security and compliance at the core.',
    'security.encryption': 'Bank-Grade Security',
    'security.encryption.desc': 'Enterprise-level security headers protect every interaction',
    'security.privacy': 'Zero Data Retention',
    'security.privacy.desc': 'All calculations happen in your browser. Nothing is stored.',
    'security.irdai': 'IRDAI Registered',
    'security.irdai.desc': 'Fully compliant with insurance regulatory standards',
    'security.support': '24/7 Claim Support',
    'security.support.desc': 'Round-the-clock assistance for all your insurance claims',

    'steps.title': 'Start Your Financial Journey',
    'steps.desc': 'Three simple steps to financial clarity.',
    'steps.1.title': 'Choose a Tool',
    'steps.1.desc': 'Pick from our suite of free financial calculators',
    'steps.2.title': 'Input Your Numbers',
    'steps.2.desc': 'Enter your financial details — everything stays private',
    'steps.3.title': 'Get Insights',
    'steps.3.desc': 'Receive personalized recommendations and clear results',

    'why.title': 'Why Choose Hanvitt Advisors?',
    'why.fiduciary.title': 'Fiduciary Standard',
    'why.fiduciary.desc': 'We always act in your best interest, providing unbiased advice tailored to your needs.',
    'why.strategy.title': 'Comprehensive Strategy',
    'why.strategy.desc': 'We look at your entire financial picture, not just investments, to build a robust plan.',
    'why.privacy.title': 'Zero-Data Retention Tools',
    'why.privacy.desc': 'Our online tools are designed with privacy first. Your data never leaves your browser.',
    'why.cta': 'Get Started Today',

    'footer.description': 'Dedicated to preserving and growing your wealth through strategic financial planning and expert guidance.',
    'footer.contact': 'Contact Us',
    'footer.location': 'Hyderabad, India',
    'footer.certifications': 'Certifications',
    'footer.regulatory': 'Hanvitt Advisors is a professional firm. Our calculators provide estimates, but personalized guidance is provided only through formal engagement.',
    'footer.rights': 'All rights reserved.',
    'footer.claims': 'Claim Support: Available 24/7',
    'footer.disclaimer': 'Disclaimer: Hanvitt Advisors is IRDAI Registered (Insurance Regulatory and Development Authority of India) but NOT SEBI Registered (Securities and Exchange Board of India).',
    'footer.quickLinks': 'Quick Links',

    'calc.privacy.badge': 'Your financial data never leaves your browser.',
    'calc.max': 'Max',
    'calc.years': 'Years',

    'savings.title': 'Savings Lab',
    'savings.desc': 'Visualize the power of compound interest over time.',
    'savings.card.title': 'Compound Interest Calculator',
    'savings.card.desc': 'Adjust the parameters to see how your money grows.',
    'savings.totalValue': 'Total Value',
    'savings.totalInterest': 'Total Interest Earned',
    'savings.balance': 'Total Balance',
    'savings.principal': 'Principal Invested',
    'savings.initial': 'Initial Deposit',
    'savings.monthly': 'Monthly Contribution',
    'savings.rate': 'Interest Rate',
    'savings.period': 'Time Period',

    'gap.title': 'The Gap Analysis',
    'gap.desc': 'Insurance & Retirement Predictor using 6% inflation and the 4% rule.',
    'gap.card.title': 'Retirement Corpus Calculator',
    'gap.card.desc': 'Estimate the nest egg you need to maintain your current lifestyle.',
    'gap.targetCorpus': 'Target Corpus',
    'gap.futureExpenses': 'Future Annual Expenses',
    'gap.inflationAdjusted': 'Adjusted for 6% inflation over',
    'gap.safeWithdrawal': 'Based on 4% safe withdrawal rate',
    'gap.ageRange': 'Age Range',
    'gap.currentAge': 'Current Age',
    'gap.retireAge': 'Retirement Age',
    'gap.annualExpenses': 'Current Annual Expenses',
    'gap.lifestyleDesc': 'Amount needed to live comfortably today',

    'health.title': 'Health Insurance Estimator',
    'health.desc': 'Calculate recommended health coverage based on family size and medical needs.',
    'health.familySize': 'Family Members',
    'health.adults': 'Number of Adults',
    'health.kids': 'Number of Kids',
    'health.location': 'Location (City Type)',
    'health.tier1': 'Tier 1 (Metro)',
    'health.tier2': 'Tier 2 (Urban)',
    'health.tier3': 'Tier 3 (Rural)',
    'health.preexisting': 'Pre-existing Conditions?',
    'health.yes': 'Yes',
    'health.no': 'No',
    'health.recommended': 'Recommended Cover',
    'health.premium': 'Est. Annual Premium',
    'health.medicalExp': 'Monthly Medical Expenditure',
    'health.surgery': 'Planned Surgery/Condition',
    'health.surgery.none': 'None / General Coverage',
    'health.surgery.angioplasty': 'Angioplasty (₹3L - ₹5L)',
    'health.surgery.bypass': 'CABG / Bypass (₹5L - ₹8L)',
    'health.surgery.knee': 'Knee Replacement (₹4L - ₹6L)',
    'health.surgery.maternity': 'Maternity (₹1L - ₹2L)',
    'health.surgery.cataract': 'Cataract (₹50k - ₹1L)',
    'health.surgery.cancer': 'Cancer Treatment (₹10L - ₹25L)',
    'health.surgery.future_note': 'Future market price considered for recommended cover.',

    'dime.title': 'DIME Goal Tracker',
    'dime.desc': 'Debt, Income, Mortgage, Education - Calculate your true protection needs.',
    'dime.card.title': 'Protection Gap Calculator',
    'dime.card.desc': 'Identify the gap between your financial obligations and your current assets.',
    'dime.protectionGap': 'Your Protection Gap',
    'dime.recommended': 'Additional coverage recommended',
    'dime.covered': 'You are fully covered!',
    'dime.debt': 'Debt & Final Expenses',
    'dime.debtDesc': 'Unpaid loans, funeral costs',
    'dime.income': 'Income Replacement',
    'dime.incomeDesc': 'Total salary needed for family',
    'dime.mortgage': 'Mortgage Balance',
    'dime.mortgageDesc': 'Remaining home loan',
    'dime.education': 'Education Fund',
    'dime.educationDesc': 'Future college costs',
    'dime.assets': 'Existing Assets / Insurance',

    'wealth.title': 'Wealth Tracker',
    'wealth.desc': 'Track your income and expenses privately. All data stays in your browser.',
    'wealth.card.title': 'Personal Finance Tracker',
    'wealth.card.desc': 'Add your income and expenses to see where your money goes.',
    'wealth.income': 'Income',
    'wealth.expense': 'Expense',
    'wealth.amount': 'Amount (₹)',
    'wealth.category': 'Category',
    'wealth.description': 'Description',
    'wealth.date': 'Date',
    'wealth.add': 'Add Entry',
    'wealth.totalIncome': 'Total Income',
    'wealth.totalExpenses': 'Total Expenses',
    'wealth.netSavings': 'Net Savings',
    'wealth.savingsRate': 'Savings Rate',
    'wealth.recentEntries': 'Recent Entries',
    'wealth.noEntries': 'No entries yet. Add your first income or expense above.',
    'wealth.clearAll': 'Clear All Data',
    'wealth.clearConfirm': 'Are you sure? This will delete all your tracker data.',
    'wealth.byCategory': 'By Category',
    'wealth.monthly': 'Monthly Trend',
    'wealth.cat.salary': 'Salary',
    'wealth.cat.freelance': 'Freelance',
    'wealth.cat.investment': 'Investment Returns',
    'wealth.cat.rental': 'Rental Income',
    'wealth.cat.other_income': 'Other Income',
    'wealth.cat.food': 'Food & Dining',
    'wealth.cat.transport': 'Transport',
    'wealth.cat.utilities': 'Utilities',
    'wealth.cat.rent': 'Rent / EMI',
    'wealth.cat.shopping': 'Shopping',
    'wealth.cat.healthcare': 'Healthcare',
    'wealth.cat.education': 'Education',
    'wealth.cat.entertainment': 'Entertainment',
    'wealth.cat.insurance': 'Insurance',
    'wealth.cat.other_expense': 'Other Expense',
    'wealth.delete': 'Delete',

    'score.title': 'Financial Health Score',
    'score.desc': 'Get a comprehensive assessment of your financial wellness.',
    'score.card.title': 'Financial Score Calculator',
    'score.card.desc': 'Answer a few questions to see your financial health score.',
    'score.yourScore': 'Your Financial Health Score',
    'score.excellent': 'Excellent',
    'score.good': 'Good',
    'score.fair': 'Fair',
    'score.poor': 'Needs Attention',
    'score.monthlyIncome': 'Monthly Income (₹)',
    'score.monthlySavings': 'Monthly Savings (₹)',
    'score.totalDebt': 'Total Outstanding Debt (₹)',
    'score.monthlyEMI': 'Monthly EMI Payments (₹)',
    'score.emergencyFund': 'Emergency Fund (₹)',
    'score.hasHealthInsurance': 'Do you have health insurance?',
    'score.hasLifeInsurance': 'Do you have life insurance?',
    'score.hasInvestments': 'Do you invest regularly (SIP/MF/Stocks)?',
    'score.hasBudget': 'Do you follow a monthly budget?',
    'score.hasWill': 'Do you have a will or estate plan?',
    'score.calculate': 'Calculate My Score',
    'score.breakdown': 'Score Breakdown',
    'score.savingsRatio': 'Savings Ratio',
    'score.debtManagement': 'Debt Management',
    'score.emergencyReady': 'Emergency Readiness',
    'score.insuranceCover': 'Insurance Coverage',
    'score.investmentHabit': 'Investment Habits',
    'score.financialPlanning': 'Financial Planning',
    'score.recommendations': 'Recommendations',
    'score.rec.savings.good': 'Your savings rate is healthy. Keep it up!',
    'score.rec.savings.bad': 'Try to save at least 20% of your income each month.',
    'score.rec.debt.good': 'Your debt levels are manageable. Well done!',
    'score.rec.debt.bad': 'Your EMI-to-income ratio is high. Consider debt consolidation.',
    'score.rec.emergency.good': 'Your emergency fund covers 6+ months. Excellent!',
    'score.rec.emergency.bad': 'Build an emergency fund equal to 6 months of expenses.',
    'score.rec.insurance.good': 'You have good insurance coverage. Stay protected!',
    'score.rec.insurance.bad': 'Consider getting health and life insurance for protection.',
    'score.rec.invest.good': 'Regular investing builds long-term wealth. Great habit!',
    'score.rec.invest.bad': 'Start a SIP or systematic investment to grow your wealth.',
    'score.rec.planning.good': 'Having a budget and estate plan shows great discipline!',
    'score.rec.planning.bad': 'Create a monthly budget and consider making a will.',
    'score.reset': 'Reset',
    'score.yes': 'Yes',
    'score.no': 'No',
    'score.age': 'Your Age',
    'score.dependents': 'Number of Dependents',
    'score.cityTier': 'City Type',
    'score.tier1': 'Metro',
    'score.tier2': 'Urban',
    'score.tier3': 'Rural',
    'score.insuranceNote': 'Get your score with personalized Health Insurance and Term Insurance recommendations based on industry standards.',

    'ins.perYear': 'yr',
    'ins.howCalculated': 'How we calculated this',
    'ins.health.title': 'Health Insurance Recommendation',
    'ins.health.subtitle': 'Family Floater plan — covers you, spouse & children with shared sum insured.',
    'ins.health.recommended': 'Recommended Cover',
    'ins.health.premium': 'Est. Annual Premium',
    'ins.health.familySize': 'Family Size',
    'ins.health.members': 'members covered',
    'ins.health.coverBreakdown': 'Family Floater Breakdown',
    'ins.health.totalCover': 'Total Recommended Cover',
    'ins.health.familyDetails': 'Family Details (for Health Insurance)',
    'ins.health.hasSpouse': 'Include Spouse?',
    'ins.health.spouseAge': 'Spouse Age',
    'ins.health.children': 'Children',
    'ins.health.parents': 'Parents',
    'ins.health.parentAge': 'Eldest Parent Age',
    'ins.health.plan.individual': 'Individual Plan',
    'ins.health.plan.familyFloater': 'Family Floater',
    'ins.health.plan.multiGen': 'Multi-Gen Floater',
    'ins.health.breakdown.self': 'Self (Base Cover)',
    'ins.health.breakdown.spouse': 'Spouse Cover',
    'ins.health.breakdown.children': 'Children Cover',
    'ins.health.breakdown.parents': 'Parents Cover',
    'ins.health.breakdown.city': 'City Cost Adjustment',
    'ins.health.breakdown.age': 'Age Risk Adjustment',
    'ins.health.breakdown.inflation': 'Medical Inflation (8% x 5yrs)',
    'ins.health.disclaimer': '*Premiums are indicative estimates based on industry-standard rate structures. Actual premiums vary by insurer, medical history, loading charges, add-ons, and underwriting. Consult an advisor for exact quotes.',
    'ins.health.reason.floater': 'Family Floater approach — one policy covers all family members under shared sum insured',
    'ins.health.reason.metro': 'Metro city multiplier (1.5x) — higher medical costs in Tier 1 cities',
    'ins.health.reason.urban': 'Urban city multiplier (1.2x) — moderate medical cost adjustment',
    'ins.health.reason.age55': 'Age 55+ multiplier (1.4x) — elevated risk for senior members',
    'ins.health.reason.age45': 'Age 45+ multiplier (1.3x) — higher risk of lifestyle diseases',
    'ins.health.reason.age35': 'Age 35+ multiplier (1.15x) — preventive care consideration',
    'ins.health.reason.inflation': 'Medical inflation adjustment (8% annual over 5 years) to future-proof coverage',

    'ins.term.title': 'Term Insurance Recommendation',
    'ins.term.subtitle': 'Calculated using Human Life Value (HLV) method — the industry standard approach.',
    'ins.term.recommended': 'Recommended Cover',
    'ins.term.premium': 'Est. Annual Premium',
    'ins.term.formula': 'Coverage Breakdown',
    'ins.term.incomeReplace': '10x Annual Income Replacement',
    'ins.term.debtCover': 'Outstanding Debt Cover',
    'ins.term.childEdu': 'Child Education Fund (₹25L each)',
    'ins.term.totalNeed': 'Recommended Cover',
    'ins.term.disclaimer': '*Term insurance premiums are estimates based on non-smoker rates. Actual premium depends on health, habits, insurer, and policy term. Contact us for personalized quotes.',

    'ins.existing.healthCover': 'Your Current Health Insurance Sum Insured',
    'ins.existing.healthHint': 'Enter the total sum insured of your existing health insurance policy (in ₹)',
    'ins.existing.termCover': 'Your Current Term Insurance Sum Insured',
    'ins.existing.termHint': 'Enter the total sum insured of your existing term/life insurance policy (in ₹)',
    'ins.verdict.sufficient': 'Your coverage is sufficient!',
    'ins.verdict.insufficient': 'Your coverage may not be enough',
    'ins.verdict.yourCover': 'Your Existing Cover',
    'ins.verdict.recommended': 'Recommended Cover',
    'ins.verdict.gap': 'Coverage Gap',
    'ins.verdict.surplus': 'Coverage Surplus',
    'ins.term.reason.income': '10x annual income replacement to protect family lifestyle',
    'ins.term.reason.debt': 'Outstanding debt coverage to clear all liabilities',
    'ins.term.reason.dependents': 'Child education fund of ₹25L per dependent',
    'ins.term.reason.hlv': 'Human Life Value (HLV) method used — industry standard',
    'ins.term.reason.minimum': 'Minimum recommended term cover of ₹50L',

    'ins.parents.title': 'Parents Health Insurance',
    'ins.parents.subtitle': 'Separate policy recommended for parents — premiums are higher due to age-related risk.',
    'ins.parents.planType': 'Senior Citizen Plan',
    'ins.parents.breakdown': 'Parents Cover Breakdown',
    'ins.parents.disclaimer': 'It is advisable to take a separate health insurance policy for parents. Due to their higher age, including them in a family floater significantly increases the overall premium and may reduce claim benefits for younger members. A dedicated senior citizen or individual plan for parents ensures better coverage and more favorable terms.',

    'nav.info': 'The Tea',

    'info.title': 'The Tea on Insurance',
    'info.desc': 'Learn why health and term insurance are essential, backed by real data from IRDAI and real-life scenarios.',
    'info.whatIs': 'What Is It?',
    'info.keyFacts': 'Key Facts & Numbers',
    'info.realLifeExamples': 'Real-Life Scenarios',
    'info.cta': 'Ready to check your financial health and get personalized insurance recommendations?',
    'info.ctaButton': 'Check Your Fin Score',

    'info.health.title': 'Health Insurance',
    'info.health.subtitle': 'Your first line of defence against medical emergencies',
    'info.health.what': 'Health insurance covers hospitalization, surgery, and medical treatment costs. In India, medical inflation runs at 14% annually — double the general inflation. A heart bypass that costs ₹5 Lakhs today will cost ₹10 Lakhs in just 5 years. A Family Floater plan covers your entire family under a single policy with shared sum insured, making it cost-effective.',
    'info.health.fact1': 'Medical inflation in India is 14% per year — the highest in Asia. Hospital bills double every 5 years.',
    'info.health.fact2': 'Average cost of a heart surgery in a metro city: ₹3.5L to ₹8L. Cancer treatment: ₹10L to ₹30L+.',
    'info.health.fact3': 'Only 25% of Indians have any form of health insurance. The remaining 75% pay from savings or borrow.',
    'info.health.fact4': '62% of medical expenses in India are out-of-pocket — the 3rd highest globally (WHO data).',
    'info.health.fact5': 'Claims ratio of health insurance industry: 55-65%, meaning for every ₹100 collected, ₹55-65 is paid back in claims.',
    'info.health.floaterTitle': 'How Family Floater Works',
    'info.health.floaterDesc': 'In a Family Floater plan, the entire family shares a common sum insured. For example, if you buy a ₹10 Lakh Family Floater, any family member can claim up to ₹10 Lakhs. The premium is calculated based on the eldest member\'s age. This is much cheaper than buying individual policies for each member. Most insurers cover self, spouse, up to 4 children, and parents under one policy.',

    'info.health.scenario1.title': 'Rahul, 32 — Appendicitis Surgery',
    'info.health.scenario1.desc': 'Rahul had emergency appendicitis surgery. Hospital bill: ₹2.8 Lakhs. Without insurance, he would have wiped out his 6-month emergency fund. With his ₹5L floater, the entire bill was cashlessly settled. His family\'s savings stayed intact.',
    'info.health.scenario2.title': 'Priya, 45 — Mother\'s Knee Replacement',
    'info.health.scenario2.desc': 'Priya\'s mother needed bilateral knee replacement at age 68. Total cost in Hyderabad: ₹6.5 Lakhs. Because Priya had added her parents to a ₹15L multi-gen floater, ₹5.8L was covered by insurance. She only paid ₹70,000 out of pocket.',
    'info.health.scenario3.title': 'Arun, 28 — Dengue Hospitalization',
    'info.health.scenario3.desc': 'Arun was hospitalized for 8 days with severe dengue. ICU charges alone were ₹1.2 Lakhs. His employer-provided group cover of ₹3L handled the bill entirely. Without it, a young earner with no savings would have been in debt.',

    'info.term.title': 'Term Insurance',
    'info.term.subtitle': 'Pure life cover at the lowest cost — for your family\'s financial security',
    'info.term.what': 'Term insurance is a pure protection plan that pays a lump sum to your family if something happens to you during the policy term. Unlike endowment or ULIP plans, it has no savings or investment component — which keeps the premium extremely low. A 30-year-old can get ₹1 Crore cover for roughly ₹10,000 per year. It is the most recommended form of life insurance by financial advisors.',
    'info.term.fact1': 'Only 3.2% of Indians have adequate life insurance coverage (IRDAI Annual Report 2023-24).',
    'info.term.fact2': 'Average Indian life insurance cover: ₹3-5 Lakhs. Recommended: 10-15x annual income (minimum ₹50 Lakhs).',
    'info.term.fact3': 'Term insurance is 10-15x cheaper than endowment plans for the same cover amount.',
    'info.term.fact4': 'Claim settlement ratio of top term insurers: 97-99%. Almost every genuine claim gets paid.',
    'info.term.fact5': 'Delaying purchase from age 25 to 35 increases your premium by 60-80% for the same cover.',
    'info.term.hlvTitle': 'Human Life Value (HLV) Method',
    'info.term.hlvDesc': 'The HLV method calculates how much your family would need if you were no longer around. It considers: your annual income multiplied by years to retirement, outstanding debts (home loan, car loan, personal loans), and children\'s education costs (₹20-30 Lakhs per child for higher education). The formula is: (Annual Income x Years to Retirement) + Total Debts + Education Fund. Most financial planners recommend at least 10x your annual income as minimum cover.',

    'info.term.scenario1.title': 'Suresh, 35 — Protecting a Home Loan',
    'info.term.scenario1.desc': 'Suresh earns ₹8L/year and has a ₹40L home loan with 20 years remaining. Without term insurance, if something happens to him, his wife would need to repay the loan from her ₹3L salary. With a ₹1 Cr term plan (premium: ₹14,000/yr), the loan gets cleared and family has ₹60L for expenses.',
    'info.term.scenario2.title': 'Meena, 30 — Single-Income Family',
    'info.term.scenario2.desc': 'Meena is the sole earner with two kids aged 3 and 5. Annual income: ₹12L. If she is no longer around, her family needs 15+ years of income replacement plus ₹50L for children\'s education. A ₹2 Cr term plan costs her just ₹16,000/year and secures her children\'s future.',
    'info.term.scenario3.title': 'Vikram, 42 — Late Buyer Penalty',
    'info.term.scenario3.desc': 'Vikram delayed buying term insurance. At 42, his ₹1 Cr term plan costs ₹22,000/year. Had he bought at 30, it would have cost ₹10,000/year — saving ₹1.44 Lakhs over the remaining policy term. Lesson: Buy term insurance as early as possible.',

    'info.irdai.title': 'IRDAI & Indian Insurance Industry',
    'info.irdai.about': 'The Insurance Regulatory and Development Authority of India (IRDAI) regulates all insurance companies in India. Here are some important regulatory facts:',
    'info.irdai.point1': 'IRDAI mandates a minimum claim settlement ratio for all insurers, ensuring consumer protection.',
    'info.irdai.point2': 'Health insurance policies in India have a standard 30-day waiting period and 2-4 year waiting for pre-existing diseases.',
    'info.irdai.point3': 'Term insurance premiums are regulated — insurers cannot charge arbitrarily high premiums for genuine applicants.',
    'info.irdai.point4': 'Tax benefits: Health insurance premiums qualify for deduction under Section 80D (up to ₹75,000/yr). Term insurance premiums qualify under Section 80C (up to ₹1.5L/yr).',

    'info.irdai.metric1.value': '4%',
    'info.irdai.metric1.label': 'Insurance Penetration (India)',
    'info.irdai.metric2.value': '97%',
    'info.irdai.metric2.label': 'Term Claim Settlement',
    'info.irdai.metric3.value': '14%',
    'info.irdai.metric3.label': 'Medical Inflation Rate',
    'info.irdai.metric4.value': '75%',
    'info.irdai.metric4.label': 'Without Health Cover',
    'info.irdai.metric5.value': '₹6,600',
    'info.irdai.metric5.label': 'Per Capita Premium (₹)',
    'info.irdai.metric6.value': '58+',
    'info.irdai.metric6.label': 'Insurance Companies',

    'contact.title': 'Get in Touch',
    'contact.desc': 'Ready to secure your financial future? Book a professional consultation with our certified experts today.',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.office': 'Office',
    'contact.reply': 'We reply within 24 hours',
    'contact.form.title': 'Reach Us',
    'contact.form.desc': 'Click below to connect with our experts via WhatsApp or Phone.',
    'contact.whatsapp': 'Chat on WhatsApp',
    'contact.call': 'Call Us Now',
  },
  hi: {
    'nav.home': 'होम',
    'nav.savingsLab': 'सेविंग्स लैब',
    'nav.theGap': 'द गैप',
    'nav.dimeTracker': 'डाइम ट्रैकर',
    'nav.wealthTracker': 'वेल्थ ट्रैकर',
    'nav.finScore': 'फिन स्कोर',
    'nav.contact': 'संपर्क',
    'nav.call': 'कॉल',
    'nav.guidingWealth': 'संपत्ति का मार्गदर्शन',
    'nav.tools': 'टूल्स',

    'hero.title': 'संपत्ति का मार्गदर्शन.',
    'hero.subtitle': 'भविष्य की सुरक्षा.',
    'hero.description': 'आपके जीवन लक्ष्यों के अनुरूप विशेषज्ञ वित्तीय योजना। हम जटिल वित्तीय परिदृश्यों को स्पष्टता और विश्वास के साथ नेविगेट करने में आपकी मदद करते हैं।',
    'hero.cta.consultation': 'परामर्श बुक करें',
    'hero.cta.tools': 'टूल्स देखें',
    'hero.stats.clients': 'खुश क्लाइंट्स',
    'hero.stats.experience': 'साल का अनुभव',
    'hero.stats.tools': 'मुफ्त टूल्स',

    'trust.title': 'प्रमाणित विशेषज्ञता',
    'trust.description': 'हमारी टीम में प्रमाणित वित्तीय पेशेवर हैं जो विशेषज्ञ सलाह और रणनीतिक मार्गदर्शन प्रदान करने के लिए समर्पित हैं। आपका भविष्य योग्य हाथों में है।',

    'tools.title': 'वित्तीय स्वतंत्रता यहाँ शुरू होती है',
    'tools.description': 'आपकी संपत्ति की योजना बनाने, सुरक्षित करने और बढ़ाने के लिए डिज़ाइन किए गए शक्तिशाली टूल्स। सभी टूल्स आपके ब्राउज़र में प्राइवेट रूप से चलते हैं।',
    'tools.try': 'अभी आज़माएं',
    'tools.explore': 'एक्सप्लोर करें',

    'showcase.savings.tagline': 'अपने पैसे को बढ़ते देखें',
    'showcase.savings.desc': 'इंटरैक्टिव चार्ट्स के साथ चक्रवृद्धि ब्याज का जादू देखें। देखें कि छोटे मासिक योगदान कैसे समय के साथ भारी संपत्ति बना सकते हैं।',
    'showcase.gap.tagline': 'अपने सुनहरे दिनों की योजना बनाएं',
    'showcase.gap.desc': 'आराम से रिटायर होने के लिए आपको कितना चाहिए, यह सटीक रूप से जानें। मुद्रास्फीति को ध्यान में रखता है और सिद्ध 4% निकासी नियम का उपयोग करता है।',
    'showcase.dime.tagline': 'जो मायने रखता है उसकी रक्षा करें',
    'showcase.dime.desc': 'कर्ज, आय, बंधक और शिक्षा में अपनी वास्तविक बीमा ज़रूरतों की गणना करें।',
    'showcase.wealth.tagline': 'हर रुपये को ट्रैक करें',
    'showcase.wealth.desc': 'सुंदर चार्ट्स के साथ अपनी आय और खर्चों की निगरानी करें। सारा डेटा आपके ब्राउज़र में प्राइवेट रहता है।',
    'showcase.score.tagline': 'अपनी वित्तीय सेहत जानें',
    'showcase.score.desc': 'अपनी बचत, कर्ज प्रबंधन, आपातकालीन तैयारी और निवेश आदतों को मापने वाला 0-100 व्यापक स्कोर प्राप्त करें।',

    'security.title': 'आपका पैसा। आपका डेटा। आपकी प्राइवेसी।',
    'security.desc': 'सुरक्षा और अनुपालन के साथ निर्मित।',
    'security.encryption': 'बैंक-ग्रेड सुरक्षा',
    'security.encryption.desc': 'एंटरप्राइज़-स्तर सुरक्षा हेडर हर इंटरैक्शन की रक्षा करते हैं',
    'security.privacy': 'ज़ीरो डेटा रिटेंशन',
    'security.privacy.desc': 'सभी गणनाएं आपके ब्राउज़र में होती हैं। कुछ भी स्टोर नहीं किया जाता।',
    'security.irdai': 'IRDAI रजिस्टर्ड',
    'security.irdai.desc': 'बीमा नियामक मानकों का पूर्ण अनुपालन',
    'security.support': '24/7 क्लेम सपोर्ट',
    'security.support.desc': 'आपके सभी बीमा क्लेम्स के लिए चौबीसों घंटे सहायता',

    'steps.title': 'अपनी वित्तीय यात्रा शुरू करें',
    'steps.desc': 'वित्तीय स्पष्टता के लिए तीन सरल कदम।',
    'steps.1.title': 'एक टूल चुनें',
    'steps.1.desc': 'हमारे मुफ्त वित्तीय कैलकुलेटर्स में से चुनें',
    'steps.2.title': 'अपने नंबर दर्ज करें',
    'steps.2.desc': 'अपने वित्तीय विवरण दर्ज करें — सब कुछ प्राइवेट रहता है',
    'steps.3.title': 'इनसाइट्स प्राप्त करें',
    'steps.3.desc': 'व्यक्तिगत सिफारिशें और स्पष्ट परिणाम प्राप्त करें',

    'why.title': 'Hanvitt Advisors को क्यों चुनें?',
    'why.fiduciary.title': 'फिड्यूशियरी स्टैंडर्ड',
    'why.fiduciary.desc': 'हम हमेशा आपके सर्वोत्तम हित में काम करते हैं, आपकी ज़रूरतों के अनुरूप निष्पक्ष सलाह प्रदान करते हैं।',
    'why.strategy.title': 'व्यापक रणनीति',
    'why.strategy.desc': 'एक मज़बूत योजना बनाने के लिए हम सिर्फ निवेश ही नहीं, आपकी पूरी वित्तीय तस्वीर देखते हैं।',
    'why.privacy.title': 'ज़ीरो-डेटा रिटेंशन टूल्स',
    'why.privacy.desc': 'हमारे ऑनलाइन टूल्स प्राइवेसी को प्राथमिकता देकर डिज़ाइन किए गए हैं। आपका डेटा कभी आपके ब्राउज़र से बाहर नहीं जाता।',
    'why.cta': 'आज ही शुरू करें',

    'footer.description': 'रणनीतिक वित्तीय योजना और विशेषज्ञ मार्गदर्शन के माध्यम से आपकी संपत्ति को संरक्षित और बढ़ाने के लिए समर्पित।',
    'footer.contact': 'संपर्क करें',
    'footer.location': 'हैदराबाद, भारत',
    'footer.certifications': 'प्रमाणपत्र',
    'footer.regulatory': 'Hanvitt Advisors एक पेशेवर फर्म है। हमारे कैलकुलेटर अनुमान प्रदान करते हैं, लेकिन व्यक्तिगत मार्गदर्शन केवल औपचारिक जुड़ाव के माध्यम से प्रदान किया जाता है।',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    'footer.claims': 'क्लेम सपोर्ट: 24/7 उपलब्ध',
    'footer.disclaimer': 'अस्वीकरण: Hanvitt Advisors IRDAI (भारतीय बीमा नियामक एवं विकास प्राधिकरण) पंजीकृत है लेकिन SEBI (भारतीय प्रतिभूति और विनिमय बोर्ड) पंजीकृत नहीं है।',
    'footer.quickLinks': 'त्वरित लिंक्स',

    'calc.privacy.badge': 'आपका वित्तीय डेटा कभी आपके ब्राउज़र से बाहर नहीं जाता।',
    'calc.max': 'अधिकतम',
    'calc.years': 'साल',

    'savings.title': 'सेविंग्स लैब',
    'savings.desc': 'समय के साथ चक्रवृद्धि ब्याज की शक्ति देखें।',
    'savings.card.title': 'चक्रवृद्धि ब्याज कैलकुलेटर',
    'savings.card.desc': 'अपना पैसा कैसे बढ़ता है देखने के लिए पैरामीटर एडजस्ट करें।',
    'savings.totalValue': 'कुल मूल्य',
    'savings.totalInterest': 'कुल ब्याज आय',
    'savings.balance': 'कुल बैलेंस',
    'savings.principal': 'कुल निवेश',
    'savings.initial': 'प्रारंभिक जमा',
    'savings.monthly': 'मासिक योगदान',
    'savings.rate': 'ब्याज दर',
    'savings.period': 'समय अवधि',

    'gap.title': 'द गैप एनालिसिस',
    'gap.desc': '6% मुद्रास्फीति और 4% नियम का उपयोग करके बीमा और रिटायरमेंट प्रिडिक्टर।',
    'gap.card.title': 'रिटायरमेंट कॉर्पस कैलकुलेटर',
    'gap.card.desc': 'अपनी वर्तमान जीवनशैली बनाए रखने के लिए आवश्यक फंड का अनुमान लगाएं।',
    'gap.targetCorpus': 'लक्ष्य कॉर्पस',
    'gap.futureExpenses': 'भविष्य के वार्षिक खर्चे',
    'gap.inflationAdjusted': '6% मुद्रास्फीति समायोजन के बाद',
    'gap.safeWithdrawal': '4% सुरक्षित निकासी दर पर आधारित',
    'gap.ageRange': 'आयु सीमा',
    'gap.currentAge': 'वर्तमान आयु',
    'gap.retireAge': 'सेवानिवृत्ति आयु',
    'gap.annualExpenses': 'वर्तमान वार्षिक खर्चे',
    'gap.lifestyleDesc': 'आज आराम से जीने के लिए आवश्यक राशि',

    'health.title': 'हेल्थ इंश्योरेंस एस्टिमेटर',
    'health.desc': 'परिवार के आकार और चिकित्सा ज़रूरतों के आधार पर अनुशंसित हेल्थ कवरेज की गणना करें।',
    'health.familySize': 'परिवार के सदस्य',
    'health.adults': 'वयस्कों की संख्या',
    'health.kids': 'बच्चों की संख्या',
    'health.location': 'स्थान (शहर का प्रकार)',
    'health.tier1': 'टियर 1 (मेट्रो)',
    'health.tier2': 'टियर 2 (शहरी)',
    'health.tier3': 'टियर 3 (ग्रामीण)',
    'health.preexisting': 'पहले से कोई बीमारी?',
    'health.yes': 'हाँ',
    'health.no': 'नहीं',
    'health.recommended': 'अनुशंसित कवर',
    'health.premium': 'अनु. वार्षिक प्रीमियम',
    'health.medicalExp': 'मासिक चिकित्सा खर्च',
    'health.surgery': 'नियोजित सर्जरी / स्थिति',
    'health.surgery.none': 'कोई नहीं / सामान्य कवरेज',
    'health.surgery.angioplasty': 'एंजियोप्लास्टी (₹3L - ₹5L)',
    'health.surgery.bypass': 'CABG / बाइपास (₹5L - ₹8L)',
    'health.surgery.knee': 'घुटना प्रतिस्थापन (₹4L - ₹6L)',
    'health.surgery.maternity': 'प्रसूति (₹1L - ₹2L)',
    'health.surgery.cataract': 'मोतियाबिंद (₹50k - ₹1L)',
    'health.surgery.cancer': 'कैंसर उपचार (₹10L - ₹25L)',
    'health.surgery.future_note': 'अनुशंसित कवर के लिए भविष्य की बाज़ार कीमत को ध्यान में रखा गया है।',

    'dime.title': 'डाइम गोल ट्रैकर',
    'dime.desc': 'कर्ज, आय, बंधक, शिक्षा - अपनी वास्तविक सुरक्षा ज़रूरतों की गणना करें।',
    'dime.card.title': 'प्रोटेक्शन गैप कैलकुलेटर',
    'dime.card.desc': 'अपनी वित्तीय देनदारियों और मौजूदा संपत्ति के बीच के अंतर की पहचान करें।',
    'dime.protectionGap': 'आपका प्रोटेक्शन गैप',
    'dime.recommended': 'अतिरिक्त कवरेज अनुशंसित',
    'dime.covered': 'आप पूरी तरह कवर्ड हैं!',
    'dime.debt': 'कर्ज और अंतिम खर्चे',
    'dime.debtDesc': 'अदत्त ऋण, अंतिम संस्कार खर्च',
    'dime.income': 'आय प्रतिस्थापन',
    'dime.incomeDesc': 'परिवार के लिए आवश्यक कुल वेतन',
    'dime.mortgage': 'बंधक बैलेंस',
    'dime.mortgageDesc': 'शेष होम लोन',
    'dime.education': 'शिक्षा कोष',
    'dime.educationDesc': 'भविष्य की कॉलेज लागत',
    'dime.assets': 'मौजूदा संपत्ति / बीमा',

    'wealth.title': 'वेल्थ ट्रैकर',
    'wealth.desc': 'अपनी आय और खर्चों को प्राइवेट रूप से ट्रैक करें। सारा डेटा आपके ब्राउज़र में रहता है।',
    'wealth.card.title': 'पर्सनल फाइनेंस ट्रैकर',
    'wealth.card.desc': 'अपना पैसा कहाँ जाता है देखने के लिए आय और खर्चे जोड़ें।',
    'wealth.income': 'आय',
    'wealth.expense': 'खर्च',
    'wealth.amount': 'राशि (₹)',
    'wealth.category': 'श्रेणी',
    'wealth.description': 'विवरण',
    'wealth.date': 'तारीख',
    'wealth.add': 'एंट्री जोड़ें',
    'wealth.totalIncome': 'कुल आय',
    'wealth.totalExpenses': 'कुल खर्चे',
    'wealth.netSavings': 'शुद्ध बचत',
    'wealth.savingsRate': 'बचत दर',
    'wealth.recentEntries': 'हालिया एंट्रीज़',
    'wealth.noEntries': 'अभी कोई एंट्री नहीं। ऊपर अपनी पहली आय या खर्च जोड़ें।',
    'wealth.clearAll': 'सारा डेटा मिटाएं',
    'wealth.clearConfirm': 'क्या आप सुनिश्चित हैं? यह आपका सारा ट्रैकर डेटा हटा देगा।',
    'wealth.byCategory': 'श्रेणी के अनुसार',
    'wealth.monthly': 'मासिक ट्रेंड',
    'wealth.cat.salary': 'वेतन',
    'wealth.cat.freelance': 'फ्रीलांस',
    'wealth.cat.investment': 'निवेश रिटर्न',
    'wealth.cat.rental': 'किराया आय',
    'wealth.cat.other_income': 'अन्य आय',
    'wealth.cat.food': 'खाना और डाइनिंग',
    'wealth.cat.transport': 'परिवहन',
    'wealth.cat.utilities': 'यूटिलिटीज़',
    'wealth.cat.rent': 'किराया / EMI',
    'wealth.cat.shopping': 'शॉपिंग',
    'wealth.cat.healthcare': 'स्वास्थ्य सेवा',
    'wealth.cat.education': 'शिक्षा',
    'wealth.cat.entertainment': 'मनोरंजन',
    'wealth.cat.insurance': 'बीमा',
    'wealth.cat.other_expense': 'अन्य खर्च',
    'wealth.delete': 'हटाएं',

    'score.title': 'वित्तीय स्वास्थ्य स्कोर',
    'score.desc': 'अपनी वित्तीय सेहत का व्यापक मूल्यांकन प्राप्त करें।',
    'score.card.title': 'फाइनेंशियल स्कोर कैलकुलेटर',
    'score.card.desc': 'अपना वित्तीय स्वास्थ्य स्कोर देखने के लिए कुछ सवालों के जवाब दें।',
    'score.yourScore': 'आपका वित्तीय स्वास्थ्य स्कोर',
    'score.excellent': 'उत्कृष्ट',
    'score.good': 'अच्छा',
    'score.fair': 'ठीक-ठाक',
    'score.poor': 'ध्यान देने की ज़रूरत',
    'score.monthlyIncome': 'मासिक आय (₹)',
    'score.monthlySavings': 'मासिक बचत (₹)',
    'score.totalDebt': 'कुल बकाया कर्ज (₹)',
    'score.monthlyEMI': 'मासिक EMI भुगतान (₹)',
    'score.emergencyFund': 'आपातकालीन कोष (₹)',
    'score.hasHealthInsurance': 'क्या आपके पास हेल्थ इंश्योरेंस है?',
    'score.hasLifeInsurance': 'क्या आपके पास लाइफ इंश्योरेंस है?',
    'score.hasInvestments': 'क्या आप नियमित रूप से निवेश करते हैं (SIP/MF/स्टॉक्स)?',
    'score.hasBudget': 'क्या आप मासिक बजट का पालन करते हैं?',
    'score.hasWill': 'क्या आपके पास वसीयत या एस्टेट प्लान है?',
    'score.calculate': 'मेरा स्कोर कैलकुलेट करें',
    'score.breakdown': 'स्कोर ब्रेकडाउन',
    'score.savingsRatio': 'बचत अनुपात',
    'score.debtManagement': 'कर्ज प्रबंधन',
    'score.emergencyReady': 'आपातकालीन तैयारी',
    'score.insuranceCover': 'बीमा कवरेज',
    'score.investmentHabit': 'निवेश आदतें',
    'score.financialPlanning': 'वित्तीय योजना',
    'score.recommendations': 'सिफारिशें',
    'score.rec.savings.good': 'आपकी बचत दर स्वस्थ है। ऐसे ही जारी रखें!',
    'score.rec.savings.bad': 'हर महीने अपनी आय का कम से कम 20% बचाने की कोशिश करें।',
    'score.rec.debt.good': 'आपका कर्ज स्तर प्रबंधनीय है। बहुत बढ़िया!',
    'score.rec.debt.bad': 'आपका EMI-से-आय अनुपात अधिक है। कर्ज समेकन पर विचार करें।',
    'score.rec.emergency.good': 'आपका आपातकालीन कोष 6+ महीने कवर करता है। उत्कृष्ट!',
    'score.rec.emergency.bad': '6 महीने के खर्चों के बराबर आपातकालीन कोष बनाएं।',
    'score.rec.insurance.good': 'आपके पास अच्छा बीमा कवरेज है। सुरक्षित रहें!',
    'score.rec.insurance.bad': 'सुरक्षा के लिए हेल्थ और लाइफ इंश्योरेंस लेने पर विचार करें।',
    'score.rec.invest.good': 'नियमित निवेश दीर्घकालिक संपत्ति बनाता है। बढ़िया आदत!',
    'score.rec.invest.bad': 'अपनी संपत्ति बढ़ाने के लिए SIP या व्यवस्थित निवेश शुरू करें।',
    'score.rec.planning.good': 'बजट और एस्टेट प्लान होना बड़ा अनुशासन दर्शाता है!',
    'score.rec.planning.bad': 'एक मासिक बजट बनाएं और वसीयत बनाने पर विचार करें।',
    'score.reset': 'रीसेट',
    'score.yes': 'हाँ',
    'score.no': 'नहीं',
    'score.age': 'आपकी आयु',
    'score.dependents': 'आश्रितों की संख्या',
    'score.cityTier': 'शहर का प्रकार',
    'score.tier1': 'मेट्रो',
    'score.tier2': 'शहरी',
    'score.tier3': 'ग्रामीण',
    'score.insuranceNote': 'उद्योग मानकों पर आधारित व्यक्तिगत हेल्थ इंश्योरेंस और टर्म इंश्योरेंस सिफारिशों के साथ अपना स्कोर प्राप्त करें।',

    'ins.perYear': 'वर्ष',
    'ins.howCalculated': 'यह कैसे कैलकुलेट किया गया',
    'ins.health.title': 'हेल्थ इंश्योरेंस सिफारिश',
    'ins.health.subtitle': 'फैमिली फ्लोटर प्लान — आप, पति/पत्नी और बच्चों को साझा सम इंश्योर्ड के साथ कवर करता है।',
    'ins.health.recommended': 'अनुशंसित कवर',
    'ins.health.premium': 'अनु. वार्षिक प्रीमियम',
    'ins.health.familySize': 'परिवार का आकार',
    'ins.health.members': 'सदस्य कवर्ड',
    'ins.health.coverBreakdown': 'फैमिली फ्लोटर ब्रेकडाउन',
    'ins.health.totalCover': 'कुल अनुशंसित कवर',
    'ins.health.familyDetails': 'परिवार का विवरण (हेल्थ इंश्योरेंस के लिए)',
    'ins.health.hasSpouse': 'पति/पत्नी शामिल करें?',
    'ins.health.spouseAge': 'पति/पत्नी की आयु',
    'ins.health.children': 'बच्चे',
    'ins.health.parents': 'माता-पिता',
    'ins.health.parentAge': 'सबसे बड़े माता/पिता की आयु',
    'ins.health.plan.individual': 'व्यक्तिगत प्लान',
    'ins.health.plan.familyFloater': 'फैमिली फ्लोटर',
    'ins.health.plan.multiGen': 'मल्टी-जेन फ्लोटर',
    'ins.health.breakdown.self': 'स्वयं (बेस कवर)',
    'ins.health.breakdown.spouse': 'पति/पत्नी कवर',
    'ins.health.breakdown.children': 'बच्चों का कवर',
    'ins.health.breakdown.parents': 'माता-पिता का कवर',
    'ins.health.breakdown.city': 'शहर लागत समायोजन',
    'ins.health.breakdown.age': 'आयु जोखिम समायोजन',
    'ins.health.breakdown.inflation': 'चिकित्सा मुद्रास्फीति (8% x 5 वर्ष)',
    'ins.health.disclaimer': '*प्रीमियम उद्योग-मानक दर संरचनाओं पर आधारित सांकेतिक अनुमान हैं। वास्तविक प्रीमियम बीमाकर्ता, चिकित्सा इतिहास, लोडिंग शुल्क, ऐड-ऑन और अंडरराइटिंग के अनुसार भिन्न होते हैं। सटीक कोट्स के लिए सलाहकार से परामर्श करें।',
    'ins.health.reason.floater': 'फैमिली फ्लोटर दृष्टिकोण — एक पॉलिसी सभी परिवार के सदस्यों को साझा सम इंश्योर्ड के तहत कवर करती है',
    'ins.health.reason.metro': 'मेट्रो शहर गुणक (1.5x) — टियर 1 शहरों में उच्च चिकित्सा लागत',
    'ins.health.reason.urban': 'शहरी शहर गुणक (1.2x) — मध्यम चिकित्सा लागत समायोजन',
    'ins.health.reason.age55': 'आयु 55+ गुणक (1.4x) — वरिष्ठ सदस्यों के लिए बढ़ा हुआ जोखिम',
    'ins.health.reason.age45': 'आयु 45+ गुणक (1.3x) — जीवनशैली रोगों का उच्च जोखिम',
    'ins.health.reason.age35': 'आयु 35+ गुणक (1.15x) — निवारक देखभाल विचार',
    'ins.health.reason.inflation': 'कवरेज को भविष्य-प्रूफ करने के लिए चिकित्सा मुद्रास्फीति समायोजन (5 वर्षों में 8% वार्षिक)',

    'ins.term.title': 'टर्म इंश्योरेंस सिफारिश',
    'ins.term.subtitle': 'Human Life Value (HLV) विधि से गणना — उद्योग मानक दृष्टिकोण।',
    'ins.term.recommended': 'अनुशंसित कवर',
    'ins.term.premium': 'अनु. वार्षिक प्रीमियम',
    'ins.term.formula': 'कवरेज ब्रेकडाउन',
    'ins.term.incomeReplace': '10x वार्षिक आय प्रतिस्थापन',
    'ins.term.debtCover': 'बकाया कर्ज कवर',
    'ins.term.childEdu': 'बच्चों का शिक्षा कोष (₹25L प्रत्येक)',
    'ins.term.totalNeed': 'अनुशंसित कवर',
    'ins.term.disclaimer': '*टर्म इंश्योरेंस प्रीमियम गैर-धूम्रपान करने वालों की दरों पर आधारित अनुमान हैं। वास्तविक प्रीमियम स्वास्थ्य, आदतों, बीमाकर्ता और पॉलिसी अवधि पर निर्भर करता है। व्यक्तिगत कोट्स के लिए हमसे संपर्क करें।',

    'ins.existing.healthCover': 'आपका वर्तमान हेल्थ इंश्योरेंस सम इंश्योर्ड',
    'ins.existing.healthHint': 'अपनी मौजूदा हेल्थ इंश्योरेंस पॉलिसी की कुल सम इंश्योर्ड दर्ज करें (₹ में)',
    'ins.existing.termCover': 'आपका वर्तमान टर्म इंश्योरेंस सम इंश्योर्ड',
    'ins.existing.termHint': 'अपनी मौजूदा टर्म/लाइफ इंश्योरेंस पॉलिसी की कुल सम इंश्योर्ड दर्ज करें (₹ में)',
    'ins.verdict.sufficient': 'आपका कवरेज पर्याप्त है!',
    'ins.verdict.insufficient': 'आपका कवरेज पर्याप्त नहीं हो सकता',
    'ins.verdict.yourCover': 'आपका मौजूदा कवर',
    'ins.verdict.recommended': 'अनुशंसित कवर',
    'ins.verdict.gap': 'कवरेज गैप',
    'ins.verdict.surplus': 'कवरेज सरप्लस',
    'ins.term.reason.income': 'परिवार की जीवनशैली की रक्षा के लिए 10x वार्षिक आय प्रतिस्थापन',
    'ins.term.reason.debt': 'सभी देनदारियों को चुकाने के लिए बकाया कर्ज कवरेज',
    'ins.term.reason.dependents': 'प्रति आश्रित ₹25L का बच्चों का शिक्षा कोष',
    'ins.term.reason.hlv': 'Human Life Value (HLV) विधि का उपयोग — उद्योग मानक',
    'ins.term.reason.minimum': 'न्यूनतम अनुशंसित टर्म कवर ₹50L',

    'ins.parents.title': 'माता-पिता हेल्थ इंश्योरेंस',
    'ins.parents.subtitle': 'माता-पिता के लिए अलग पॉलिसी अनुशंसित — आयु-संबंधी जोखिम के कारण प्रीमियम अधिक होते हैं।',
    'ins.parents.planType': 'सीनियर सिटीज़न प्लान',
    'ins.parents.breakdown': 'माता-पिता कवर ब्रेकडाउन',
    'ins.parents.disclaimer': 'माता-पिता के लिए अलग हेल्थ इंश्योरेंस पॉलिसी लेना उचित है। उनकी अधिक आयु के कारण, उन्हें फैमिली फ्लोटर में शामिल करने से समग्र प्रीमियम काफी बढ़ जाता है और युवा सदस्यों के लिए क्लेम लाभ कम हो सकते हैं।',

    'nav.info': 'द टी',

    'info.title': 'बीमा की पूरी जानकारी',
    'info.desc': 'जानें कि हेल्थ और टर्म इंश्योरेंस क्यों ज़रूरी हैं, IRDAI और वास्तविक परिदृश्यों के डेटा से समर्थित।',
    'info.whatIs': 'यह क्या है?',
    'info.keyFacts': 'मुख्य तथ्य और आंकड़े',
    'info.realLifeExamples': 'वास्तविक परिदृश्य',
    'info.cta': 'अपनी वित्तीय सेहत जांचने और व्यक्तिगत बीमा सिफारिशें पाने के लिए तैयार हैं?',
    'info.ctaButton': 'अपना फिन स्कोर चेक करें',

    'info.health.title': 'हेल्थ इंश्योरेंस',
    'info.health.subtitle': 'चिकित्सा आपातकाल के खिलाफ आपकी पहली रक्षा पंक्ति',
    'info.health.what': 'हेल्थ इंश्योरेंस अस्पताल में भर्ती, सर्जरी और चिकित्सा उपचार की लागत को कवर करता है। भारत में चिकित्सा मुद्रास्फीति सालाना 14% है — सामान्य मुद्रास्फीति से दोगुनी। आज ₹5 लाख की हार्ट बाइपास सर्जरी सिर्फ 5 साल में ₹10 लाख हो जाएगी। फैमिली फ्लोटर प्लान आपके पूरे परिवार को साझा सम इंश्योर्ड के साथ एक ही पॉलिसी में कवर करता है।',
    'info.health.fact1': 'भारत में चिकित्सा मुद्रास्फीति सालाना 14% है — एशिया में सबसे अधिक। अस्पताल के बिल हर 5 साल में दोगुने हो जाते हैं।',
    'info.health.fact2': 'मेट्रो शहर में हार्ट सर्जरी की औसत लागत: ₹3.5L से ₹8L। कैंसर उपचार: ₹10L से ₹30L+।',
    'info.health.fact3': 'केवल 25% भारतीयों के पास किसी भी प्रकार का हेल्थ इंश्योरेंस है। शेष 75% बचत से भुगतान करते हैं या उधार लेते हैं।',
    'info.health.fact4': 'भारत में 62% चिकित्सा खर्चे जेब से होते हैं — वैश्विक स्तर पर तीसरा सबसे अधिक (WHO डेटा)।',
    'info.health.fact5': 'हेल्थ इंश्योरेंस उद्योग का क्लेम अनुपात: 55-65%, यानी हर ₹100 में से ₹55-65 क्लेम में वापस दिए जाते हैं।',
    'info.health.floaterTitle': 'फैमिली फ्लोटर कैसे काम करता है',
    'info.health.floaterDesc': 'फैमिली फ्लोटर प्लान में पूरा परिवार एक समान सम इंश्योर्ड साझा करता है। उदाहरण के लिए, यदि आप ₹10 लाख का फैमिली फ्लोटर खरीदते हैं, तो कोई भी परिवार का सदस्य ₹10 लाख तक का क्लेम कर सकता है। प्रीमियम सबसे बड़े सदस्य की आयु के आधार पर गणना किया जाता है।',

    'info.health.scenario1.title': 'राहुल, 32 — एपेंडिसाइटिस सर्जरी',
    'info.health.scenario1.desc': 'राहुल की आपातकालीन एपेंडिसाइटिस सर्जरी हुई। अस्पताल का बिल: ₹2.8 लाख। बीमा के बिना, उनका 6 महीने का इमरजेंसी फंड खत्म हो जाता। ₹5L फ्लोटर से पूरा बिल कैशलेस सेटल हो गया।',
    'info.health.scenario2.title': 'प्रिया, 45 — माँ का घुटना प्रतिस्थापन',
    'info.health.scenario2.desc': 'प्रिया की माँ को 68 साल की उम्र में दोनों घुटनों का प्रतिस्थापन चाहिए था। हैदराबाद में कुल लागत: ₹6.5 लाख। ₹15L मल्टी-जेन फ्लोटर से ₹5.8L बीमा से कवर हुआ।',
    'info.health.scenario3.title': 'अरुण, 28 — डेंगू अस्पताल में भर्ती',
    'info.health.scenario3.desc': 'अरुण 8 दिनों तक गंभीर डेंगू से अस्पताल में भर्ती रहे। सिर्फ ICU का खर्चा ₹1.2 लाख था। नियोक्ता द्वारा दिए गए ₹3L के ग्रुप कवर ने पूरा बिल संभाला।',

    'info.term.title': 'टर्म इंश्योरेंस',
    'info.term.subtitle': 'सबसे कम लागत पर शुद्ध लाइफ कवर — आपके परिवार की वित्तीय सुरक्षा के लिए',
    'info.term.what': 'टर्म इंश्योरेंस एक शुद्ध सुरक्षा योजना है जो पॉलिसी अवधि के दौरान आपको कुछ होने पर आपके परिवार को एकमुश्त राशि देती है। एंडोमेंट या ULIP प्लान्स के विपरीत, इसमें कोई बचत या निवेश घटक नहीं है — जो प्रीमियम को बेहद कम रखता है।',
    'info.term.fact1': 'केवल 3.2% भारतीयों के पास पर्याप्त लाइफ इंश्योरेंस कवरेज है (IRDAI वार्षिक रिपोर्ट 2023-24)।',
    'info.term.fact2': 'औसत भारतीय लाइफ इंश्योरेंस कवर: ₹3-5 लाख। अनुशंसित: वार्षिक आय का 10-15x (न्यूनतम ₹50 लाख)।',
    'info.term.fact3': 'टर्म इंश्योरेंस समान कवर राशि के लिए एंडोमेंट प्लान्स से 10-15x सस्ता है।',
    'info.term.fact4': 'शीर्ष टर्म बीमाकर्ताओं का क्लेम सेटलमेंट अनुपात: 97-99%। लगभग हर वास्तविक क्लेम का भुगतान होता है।',
    'info.term.fact5': '25 से 35 साल की उम्र तक खरीदारी में देरी करने से समान कवर के लिए प्रीमियम 60-80% बढ़ जाता है।',
    'info.term.hlvTitle': 'Human Life Value (HLV) विधि',
    'info.term.hlvDesc': 'HLV विधि गणना करती है कि यदि आप न रहें तो आपके परिवार को कितनी राशि की आवश्यकता होगी। इसमें शामिल है: वार्षिक आय गुणा रिटायरमेंट तक के वर्ष, बकाया कर्ज, और बच्चों की शिक्षा लागत (₹20-30 लाख प्रति बच्चा)। अधिकांश वित्तीय योजनाकार न्यूनतम कवर के रूप में वार्षिक आय का कम से कम 10x अनुशंसित करते हैं।',

    'info.term.scenario1.title': 'सुरेश, 35 — होम लोन की सुरक्षा',
    'info.term.scenario1.desc': 'सुरेश ₹8L/वर्ष कमाते हैं और 20 साल बाकी ₹40L होम लोन है। ₹1 करोड़ के टर्म प्लान (प्रीमियम: ₹14,000/वर्ष) से लोन चुक जाता है और परिवार के पास ₹60L बचते हैं।',
    'info.term.scenario2.title': 'मीना, 30 — एकल-आय परिवार',
    'info.term.scenario2.desc': 'मीना 3 और 5 साल के दो बच्चों के साथ एकमात्र कमाने वाली हैं। वार्षिक आय: ₹12L। ₹2 करोड़ के टर्म प्लान की लागत सिर्फ ₹16,000/वर्ष है।',
    'info.term.scenario3.title': 'विक्रम, 42 — देर से खरीदने का नुकसान',
    'info.term.scenario3.desc': 'विक्रम ने टर्म इंश्योरेंस खरीदने में देरी की। 42 पर ₹1 करोड़ प्लान ₹22,000/वर्ष लागत आता है। 30 पर खरीदा होता तो ₹10,000/वर्ष होता। सबक: जल्द से जल्द खरीदें।',

    'info.irdai.title': 'IRDAI और भारतीय बीमा उद्योग',
    'info.irdai.about': 'IRDAI (भारतीय बीमा नियामक एवं विकास प्राधिकरण) भारत में सभी बीमा कंपनियों को नियंत्रित करता है। कुछ महत्वपूर्ण नियामक तथ्य:',
    'info.irdai.point1': 'IRDAI सभी बीमाकर्ताओं के लिए न्यूनतम क्लेम सेटलमेंट अनुपात अनिवार्य करता है।',
    'info.irdai.point2': 'हेल्थ इंश्योरेंस पॉलिसियों में मानक 30 दिन की प्रतीक्षा अवधि और पहले से मौजूद बीमारियों के लिए 2-4 साल की प्रतीक्षा होती है।',
    'info.irdai.point3': 'टर्म इंश्योरेंस प्रीमियम नियंत्रित हैं — बीमाकर्ता मनमाने ढंग से उच्च प्रीमियम नहीं ले सकते।',
    'info.irdai.point4': 'कर लाभ: हेल्थ इंश्योरेंस प्रीमियम धारा 80D के तहत (₹75,000/वर्ष तक)। टर्म इंश्योरेंस प्रीमियम धारा 80C के तहत (₹1.5L/वर्ष तक)।',

    'info.irdai.metric1.value': '4%',
    'info.irdai.metric1.label': 'बीमा पैठ (भारत)',
    'info.irdai.metric2.value': '97%',
    'info.irdai.metric2.label': 'टर्म क्लेम सेटलमेंट',
    'info.irdai.metric3.value': '14%',
    'info.irdai.metric3.label': 'चिकित्सा मुद्रास्फीति दर',
    'info.irdai.metric4.value': '75%',
    'info.irdai.metric4.label': 'हेल्थ कवर के बिना',
    'info.irdai.metric5.value': '₹6,600',
    'info.irdai.metric5.label': 'प्रति व्यक्ति प्रीमियम (₹)',
    'info.irdai.metric6.value': '58+',
    'info.irdai.metric6.label': 'बीमा कंपनियां',

    'contact.title': 'संपर्क करें',
    'contact.desc': 'अपना वित्तीय भविष्य सुरक्षित करने के लिए तैयार हैं? आज ही हमारे प्रमाणित विशेषज्ञों के साथ पेशेवर परामर्श बुक करें।',
    'contact.phone': 'फोन',
    'contact.email': 'ईमेल',
    'contact.office': 'कार्यालय',
    'contact.reply': 'हम 24 घंटे में जवाब देते हैं',
    'contact.form.title': 'हमसे जुड़ें',
    'contact.form.desc': 'WhatsApp या फोन से हमारे विशेषज्ञों से जुड़ने के लिए नीचे क्लिक करें।',
    'contact.whatsapp': 'WhatsApp पर चैट करें',
    'contact.call': 'अभी कॉल करें',
  },
  te: {
    'nav.home': 'హోమ్',
    'nav.savingsLab': 'సేవింగ్స్ ల్యాబ్',
    'nav.theGap': 'ది గ్యాప్',
    'nav.dimeTracker': 'డైమ్ ట్రాకర్',
    'nav.wealthTracker': 'వెల్త్ ట్రాకర్',
    'nav.finScore': 'ఫిన్ స్కోర్',
    'nav.contact': 'కాంటాక్ట్',
    'nav.call': 'కాల్',
    'nav.guidingWealth': 'సంపదకు మార్గదర్శకం',
    'nav.tools': 'టూల్స్',

    'hero.title': 'సంపదకు మార్గదర్శకం.',
    'hero.subtitle': 'భవిష్యత్తుకు రక్షణ.',
    'hero.description': 'మీ జీవిత లక్ష్యాలకు అనుగుణంగా నిపుణులైన ఆర్థిక ప్రణాళిక. స్పష్టత మరియు విశ్వాసంతో సంక్లిష్టమైన ఆర్థిక పరిస్థితులను నావిగేట్ చేయడంలో మేము మీకు సహాయం చేస్తాము.',
    'hero.cta.consultation': 'కన్సల్టేషన్ బుక్ చేయండి',
    'hero.cta.tools': 'టూల్స్‌ను అన్వేషించండి',
    'hero.stats.clients': 'సంతోషకరమైన క్లయింట్లు',
    'hero.stats.experience': 'సంవత్సరం అనుభవం',
    'hero.stats.tools': 'ఉచిత సాధనాలు',

    'trust.title': 'ధృవీకరించబడిన నైపుణ్యం',
    'trust.description': 'మా బృందంలో నిపుణుల సలహాలు మరియు వ్యూహాత్మక మార్గదర్శకత్వం అందించడానికి అంకితమైన ధృవీకరించబడిన ఆర్థిక నిపుణులు ఉన్నారు. మీ భవిష్యత్తు సురక్షితమైన చేతుల్లో ఉంది.',

    'tools.title': 'ఆర్థిక స్వేచ్ఛ ఇక్కడ ప్రారంభమవుతుంది',
    'tools.description': 'మీ సంపదను ప్లాన్ చేయడానికి, రక్షించడానికి మరియు పెంచడానికి రూపొందించిన శక్తివంతమైన సాధనాలు. అన్ని సాధనాలు మీ బ్రౌజర్‌లో ప్రైవేట్‌గా నడుస్తాయి.',
    'tools.try': 'ఇప్పుడే ప్రయత్నించండి',
    'tools.explore': 'అన్వేషించండి',

    'showcase.savings.tagline': 'మీ డబ్బు పెరుగుదలను చూడండి',
    'showcase.savings.desc': 'ఇంటరాక్టివ్ చార్ట్‌లతో చక్రవడ్డీ మ్యాజిక్‌ను విజువలైజ్ చేయండి. చిన్న నెలవారీ సహకారాలు కాలక్రమేణా భారీ సంపదను ఎలా నిర్మించగలవో చూడండి.',
    'showcase.gap.tagline': 'మీ స్వర్ణయుగాన్ని ప్లాన్ చేయండి',
    'showcase.gap.desc': 'సుఖంగా రిటైర్ అవ్వడానికి మీకు ఎంత అవసరమో ఖచ్చితంగా తెలుసుకోండి. ద్రవ్యోల్బణాన్ని పరిగణిస్తుంది మరియు నిరూపితమైన 4% ఉపసంహరణ నియమాన్ని ఉపయోగిస్తుంది.',
    'showcase.dime.tagline': 'ముఖ్యమైనదాన్ని రక్షించుకోండి',
    'showcase.dime.desc': 'అప్పు, ఆదాయం, తనఖా మరియు విద్యలో మీ నిజమైన ఇన్సూరెన్స్ అవసరాలను లెక్కించండి.',
    'showcase.wealth.tagline': 'ప్రతి రూపాయిని ట్రాక్ చేయండి',
    'showcase.wealth.desc': 'అందమైన చార్ట్‌లతో మీ ఆదాయం మరియు ఖర్చులను పర్యవేక్షించండి. మొత్తం డేటా మీ బ్రౌజర్‌లో ప్రైవేట్‌గా ఉంటుంది.',
    'showcase.score.tagline': 'మీ ఆర్థిక ఆరోగ్యాన్ని తెలుసుకోండి',
    'showcase.score.desc': 'మీ పొదుపు, అప్పు నిర్వహణ, అత్యవసర సంసిద్ధత మరియు పెట్టుబడి అలవాట్లను కొలిచే 0-100 సమగ్ర స్కోర్ పొందండి.',

    'security.title': 'మీ డబ్బు. మీ డేటా. మీ గోప్యత.',
    'security.desc': 'భద్రత మరియు అనుగుణ్యతతో నిర్మించబడింది.',
    'security.encryption': 'బ్యాంక్-గ్రేడ్ భద్రత',
    'security.encryption.desc': 'ఎంటర్‌ప్రైజ్-స్థాయి భద్రతా హెడర్లు ప్రతి ఇంటరాక్షన్‌ను రక్షిస్తాయి',
    'security.privacy': 'జీరో డేటా రిటెన్షన్',
    'security.privacy.desc': 'అన్ని గణనలు మీ బ్రౌజర్‌లో జరుగుతాయి. ఏదీ నిల్వ చేయబడదు.',
    'security.irdai': 'IRDAI రిజిస్టర్డ్',
    'security.irdai.desc': 'ఇన్సూరెన్స్ నియంత్రణ ప్రమాణాలకు పూర్తిగా అనుగుణం',
    'security.support': '24/7 క్లెయిమ్ సపోర్ట్',
    'security.support.desc': 'మీ అన్ని ఇన్సూరెన్స్ క్లెయిమ్‌లకు రౌండ్-ది-క్లాక్ సహాయం',

    'steps.title': 'మీ ఆర్థిక ప్రయాణాన్ని ప్రారంభించండి',
    'steps.desc': 'ఆర్థిక స్పష్టత కోసం మూడు సాధారణ దశలు.',
    'steps.1.title': 'ఒక సాధనాన్ని ఎంచుకోండి',
    'steps.1.desc': 'మా ఉచిత ఆర్థిక కాలిక్యులేటర్ల సూట్ నుండి ఎంచుకోండి',
    'steps.2.title': 'మీ నంబర్లను నమోదు చేయండి',
    'steps.2.desc': 'మీ ఆర్థిక వివరాలను నమోదు చేయండి — అంతా ప్రైవేట్‌గా ఉంటుంది',
    'steps.3.title': 'ఇన్‌సైట్స్ పొందండి',
    'steps.3.desc': 'వ్యక్తిగతీకరించిన సిఫార్సులు మరియు స్పష్టమైన ఫలితాలను పొందండి',

    'why.title': 'హన్విత్ అడ్వైజర్స్‌ను ఎందుకు ఎంచుకోవాలి?',
    'why.fiduciary.title': 'ఫిడ్యూషియరీ స్టాండర్డ్',
    'why.fiduciary.desc': 'మేము ఎల్లప్పుడూ మీ ప్రయోజనం కోసం పని చేస్తాము, మీ అవసరాలకు తగిన నిష్పక్షపాత సలహాలను అందిస్తాము.',
    'why.strategy.title': 'సమగ్ర వ్యూహం',
    'why.strategy.desc': 'బలమైన ప్రణాళికను రూపొందించడానికి మేము కేవలం పెట్టుబడులనే కాకుండా మీ మొత్తం ఆర్థిక చిత్రాన్ని పరిశీలిస్తాము.',
    'why.privacy.title': 'జీరో-డేటా రిటెన్షన్ టూల్స్',
    'why.privacy.desc': 'మా ఆన్‌లైన్ టూల్స్ గోప్యతకు ప్రాధాన్యత ఇచ్చేలా రూపొందించబడ్డాయి. మీ డేటా ఎప్పుడూ మీ బ్రౌజర్ నుండి బయటకు వెళ్లదు.',
    'why.cta': 'ఈరోజే ప్రారంభించండి',

    'footer.description': 'వ్యూహాత్మక ఆర్థిక ప్రణాళిక మరియు నిపుణుల మార్గదర్శకత్వం ద్వారా మీ సంపదను కాపాడటానికి మరియు పెంచడానికి అంకితం చేయబడింది.',
    'footer.contact': 'మమ్మల్ని సంప్రదించండి',
    'footer.location': 'హైదరాబాద్, ఇండియా',
    'footer.certifications': 'సర్టిఫికేషన్స్',
    'footer.regulatory': 'హన్విత్ అడ్వైజర్స్ ఒక ప్రొఫెషనల్ సంస్థ. మా కాలిక్యులేటర్లు అంచనాలను అందిస్తాయి, కానీ వ్యక్తిగత మార్గదర్శకత్వం కేవలం అధికారిక ఒప్పందం ద్వారా మాత్రమే అందించబడుతుంది.',
    'footer.rights': 'అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.',
    'footer.claims': 'క్లెయిమ్ సపోర్ట్: 24/7 అందుబాటులో ఉంటుంది',
    'footer.disclaimer': 'గమనిక: హన్విత్ అడ్వైజర్స్ IRDAI (భారత ఇన్సూరెన్స్ నియంత్రణ మరియు అభివృద్ధి సంస్థ) రిజిస్టర్డ్ సంస్థ, కానీ SEBI (భారత సెక్యూరిటీస్ అండ్ ఎక్స్ఛేంజ్ బోర్డ్) రిజిస్టర్డ్ సంస్థ కాదు.',
    'footer.quickLinks': 'త్వరిత లింక్‌లు',

    'calc.privacy.badge': 'మీ ఆర్థిక డేటా ఎప్పుడూ మీ బ్రౌజర్ నుండి బయటకు వెళ్లదు.',
    'calc.max': 'గరిష్ట',
    'calc.years': 'సంవత్సరాలు',

    'savings.title': 'సేవింగ్స్ ల్యాబ్',
    'savings.desc': 'కాలక్రమేణా చక్రవడ్డీ శక్తిని విజువలైజ్ చేయండి.',
    'savings.card.title': 'చక్రవడ్డీ కాలిక్యులేటర్',
    'savings.card.desc': 'మీ డబ్బు ఎలా పెరుగుతుందో చూడటానికి పారామితులను సర్దుబాటు చేయండి.',
    'savings.totalValue': 'మొత్తం విలువ',
    'savings.totalInterest': 'మొత్తం వడ్డీ ఆదాయం',
    'savings.balance': 'మొత్తం బ్యాలెన్స్',
    'savings.principal': 'మొత్తం పెట్టుబడి',
    'savings.initial': 'ప్రారంభ డిపాజిట్',
    'savings.monthly': 'నెలవారీ సహకారం',
    'savings.rate': 'వడ్డీ రేటు',
    'savings.period': 'సమయ కాలం',

    'gap.title': 'ది గ్యాప్ అనాలిసిస్',
    'gap.desc': '6% ద్రవ్యోల్బణం మరియు 4% నియమాన్ని ఉపయోగించి ఇన్సూరెన్స్ & రిటైర్మెంట్ ప్రిడిక్టర్.',
    'gap.card.title': 'రిటైర్మెంట్ కార్పస్ కాలిక్యులేటర్',
    'gap.card.desc': 'మీ ప్రస్తుత జీవనశైలిని కొనసాగించడానికి మీకు అవసరమైన నిధిని అంచనా వేయండి.',
    'gap.targetCorpus': 'లక్ష్య నిధి',
    'gap.futureExpenses': 'భవిష్యత్ వార్షిక ఖర్చులు',
    'gap.inflationAdjusted': '6% ద్రవ్యోల్బణం సర్దుబాటు తర్వాత',
    'gap.safeWithdrawal': '4% సురక్షిత ఉపసంహరణ రేటు ఆధారంగా',
    'gap.ageRange': 'వయస్సు పరిధి',
    'gap.currentAge': 'ప్రస్తుత వయస్సు',
    'gap.retireAge': 'రిటైర్మెంట్ వయస్సు',
    'gap.annualExpenses': 'ప్రస్తుత వార్షిక ఖర్చులు',
    'gap.lifestyleDesc': 'ఈరోజు సౌకర్యవంతంగా జీవించడానికి అవసరమైన మొత్తం',

    'health.title': 'హెల్త్ ఇన్సూరెన్స్ ఎస్టిమేటర్',
    'health.desc': 'కుటుంబ సభ్యుల సంఖ్య మరియు వైద్య అవసరాల ఆధారంగా సిఫార్సు చేయబడిన హెల్త్ కవరేజీని లెక్కించండి.',
    'health.familySize': 'కుటుంబ సభ్యులు',
    'health.adults': 'పెద్దల సంఖ్య',
    'health.kids': 'పిల్లల సంఖ్య',
    'health.location': 'ప్రాంతం (నగరం రకం)',
    'health.tier1': 'టైర్ 1 (మెట్రో)',
    'health.tier2': 'టైర్ 2 (పట్టణ)',
    'health.tier3': 'టైర్ 3 (గ్రామీణ)',
    'health.preexisting': 'ముందుగా ఉన్న అనారోగ్య సమస్యలు?',
    'health.yes': 'అవును',
    'health.no': 'కాదు',
    'health.recommended': 'సిఫార్సు చేయబడిన కవర్',
    'health.premium': 'అంచనా వార్షిక ప్రీమియం',
    'health.medicalExp': 'నెలవారీ వైద్య ఖర్చులు',
    'health.surgery': 'ప్లాన్ చేసిన సర్జరీ / అనారోగ్యం',
    'health.surgery.none': 'ఏదీ లేదు / సాధారణ కవరేజీ',
    'health.surgery.angioplasty': 'యాంజియోప్లాస్టీ (₹3L - ₹5L)',
    'health.surgery.bypass': 'బైపాస్ సర్జరీ (₹5L - ₹8L)',
    'health.surgery.knee': 'మోకాలి మార్పిడి (₹4L - ₹6L)',
    'health.surgery.maternity': 'ప్రసూతి (₹1L - ₹2L)',
    'health.surgery.cataract': 'కంటి శుక్లం (₹50k - ₹1L)',
    'health.surgery.cancer': 'క్యాన్సర్ చికిత్స (₹10L - ₹25L)',
    'health.surgery.future_note': 'సిఫార్సు చేయబడిన కవర్ కోసం భవిష్యత్తు మార్కెట్ ధర పరిగణనలోకి తీసుకోబడింది.',

    'dime.title': 'డైమ్ గోల్ ట్రాకర్',
    'dime.desc': 'అప్పు, ఆదాయం, తనఖా, విద్య - మీ నిజమైన రక్షణ అవసరాలను లెక్కించండి.',
    'dime.card.title': 'ప్రొటెక్షన్ గ్యాప్ కాలిక్యులేటర్',
    'dime.card.desc': 'మీ ఆర్థిక బాధ్యతలు మరియు మీ ప్రస్తుత ఆస్తుల మధ్య వ్యత్యాసాన్ని గుర్తించండి.',
    'dime.protectionGap': 'మీ రక్షణ గ్యాప్',
    'dime.recommended': 'అదనపు కవరేజ్ సిఫార్సు చేయబడింది',
    'dime.covered': 'మీరు పూర్తిగా కవర్ చేయబడ్డారు!',
    'dime.debt': 'అప్పు & తుది ఖర్చులు',
    'dime.debtDesc': 'చెల్లించని రుణాలు, అంత్యక్రియల ఖర్చులు',
    'dime.income': 'ఆదాయ భర్తీ',
    'dime.incomeDesc': 'కుటుంబం కోసం అవసరమైన మొత్తం జీతం',
    'dime.mortgage': 'తనఖా బ్యాలెన్స్',
    'dime.mortgageDesc': 'మిగిలిన హోమ్ లోన్',
    'dime.education': 'విద్యా నిధి',
    'dime.educationDesc': 'భవిష్యత్ కళాశాల ఖర్చులు',
    'dime.assets': 'ప్రస్తుత ఆస్తులు / ఇన్సూరెన్స్',

    'wealth.title': 'వెల్త్ ట్రాకర్',
    'wealth.desc': 'మీ ఆదాయం మరియు ఖర్చులను ప్రైవేట్‌గా ట్రాక్ చేయండి. మొత్తం డేటా మీ బ్రౌజర్‌లో ఉంటుంది.',
    'wealth.card.title': 'వ్యక్తిగత ఫైనాన్స్ ట్రాకర్',
    'wealth.card.desc': 'మీ డబ్బు ఎక్కడికి వెళ్తుందో చూడటానికి మీ ఆదాయం మరియు ఖర్చులను జోడించండి.',
    'wealth.income': 'ఆదాయం',
    'wealth.expense': 'ఖర్చు',
    'wealth.amount': 'మొత్తం (₹)',
    'wealth.category': 'వర్గం',
    'wealth.description': 'వివరణ',
    'wealth.date': 'తేదీ',
    'wealth.add': 'ఎంట్రీ జోడించు',
    'wealth.totalIncome': 'మొత్తం ఆదాయం',
    'wealth.totalExpenses': 'మొత్తం ఖర్చులు',
    'wealth.netSavings': 'నికర పొదుపు',
    'wealth.savingsRate': 'పొదుపు రేటు',
    'wealth.recentEntries': 'ఇటీవలి ఎంట్రీలు',
    'wealth.noEntries': 'ఇంకా ఎంట్రీలు లేవు. పైన మీ మొదటి ఆదాయం లేదా ఖర్చును జోడించండి.',
    'wealth.clearAll': 'మొత్తం డేటా క్లియర్ చేయండి',
    'wealth.clearConfirm': 'మీరు ఖచ్చితంగా ఉన్నారా? ఇది మీ ట్రాకర్ డేటా మొత్తాన్ని తొలగిస్తుంది.',
    'wealth.byCategory': 'వర్గం వారీగా',
    'wealth.monthly': 'నెలవారీ ట్రెండ్',
    'wealth.cat.salary': 'జీతం',
    'wealth.cat.freelance': 'ఫ్రీలాన్స్',
    'wealth.cat.investment': 'పెట్టుబడి రాబడి',
    'wealth.cat.rental': 'అద్దె ఆదాయం',
    'wealth.cat.other_income': 'ఇతర ఆదాయం',
    'wealth.cat.food': 'ఆహారం & డైనింగ్',
    'wealth.cat.transport': 'రవాణా',
    'wealth.cat.utilities': 'యుటిలిటీలు',
    'wealth.cat.rent': 'అద్దె / EMI',
    'wealth.cat.shopping': 'షాపింగ్',
    'wealth.cat.healthcare': 'ఆరోగ్య సంరక్షణ',
    'wealth.cat.education': 'విద్య',
    'wealth.cat.entertainment': 'వినోదం',
    'wealth.cat.insurance': 'ఇన్సూరెన్స్',
    'wealth.cat.other_expense': 'ఇతర ఖర్చు',
    'wealth.delete': 'తొలగించు',

    'score.title': 'ఆర్థిక ఆరోగ్య స్కోర్',
    'score.desc': 'మీ ఆర్థిక ఆరోగ్యం యొక్క సమగ్ర అంచనా పొందండి.',
    'score.card.title': 'ఫైనాన్షియల్ స్కోర్ కాలిక్యులేటర్',
    'score.card.desc': 'మీ ఆర్థిక ఆరోగ్య స్కోర్ చూడటానికి కొన్ని ప్రశ్నలకు సమాధానం ఇవ్వండి.',
    'score.yourScore': 'మీ ఆర్థిక ఆరోగ్య స్కోర్',
    'score.excellent': 'అద్భుతం',
    'score.good': 'మంచిది',
    'score.fair': 'సరిపోతుంది',
    'score.poor': 'శ్రద్ధ అవసరం',
    'score.monthlyIncome': 'నెలవారీ ఆదాయం (₹)',
    'score.monthlySavings': 'నెలవారీ పొదుపు (₹)',
    'score.totalDebt': 'మొత్తం బాకీ ఉన్న అప్పు (₹)',
    'score.monthlyEMI': 'నెలవారీ EMI చెల్లింపులు (₹)',
    'score.emergencyFund': 'అత్యవసర నిధి (₹)',
    'score.hasHealthInsurance': 'మీకు హెల్త్ ఇన్సూరెన్స్ ఉందా?',
    'score.hasLifeInsurance': 'మీకు లైఫ్ ఇన్సూరెన్స్ ఉందా?',
    'score.hasInvestments': 'మీరు క్రమం తప్పకుండా పెట్టుబడి పెడుతున్నారా (SIP/MF/స్టాక్స్)?',
    'score.hasBudget': 'మీరు నెలవారీ బడ్జెట్‌ను అనుసరిస్తున్నారా?',
    'score.hasWill': 'మీకు వీలునామా లేదా ఎస్టేట్ ప్లాన్ ఉందా?',
    'score.calculate': 'నా స్కోర్ లెక్కించండి',
    'score.breakdown': 'స్కోర్ విభజన',
    'score.savingsRatio': 'పొదుపు నిష్పత్తి',
    'score.debtManagement': 'అప్పు నిర్వహణ',
    'score.emergencyReady': 'అత్యవసర సంసిద్ధత',
    'score.insuranceCover': 'ఇన్సూరెన్స్ కవరేజ్',
    'score.investmentHabit': 'పెట్టుబడి అలవాట్లు',
    'score.financialPlanning': 'ఆర్థిక ప్రణాళిక',
    'score.recommendations': 'సిఫార్సులు',
    'score.rec.savings.good': 'మీ పొదుపు రేటు ఆరోగ్యకరంగా ఉంది. కొనసాగించండి!',
    'score.rec.savings.bad': 'ప్రతి నెలా మీ ఆదాయంలో కనీసం 20% పొదుపు చేయడానికి ప్రయత్నించండి.',
    'score.rec.debt.good': 'మీ అప్పు స్థాయిలు నిర్వహించదగినవి. బాగా చేశారు!',
    'score.rec.debt.bad': 'మీ EMI-ఆదాయ నిష్పత్తి ఎక్కువగా ఉంది. అప్పు ఏకీకరణను పరిగణించండి.',
    'score.rec.emergency.good': 'మీ అత్యవసర నిధి 6+ నెలలను కవర్ చేస్తుంది. అద్భుతం!',
    'score.rec.emergency.bad': '6 నెలల ఖర్చులకు సమానమైన అత్యవసర నిధిని నిర్మించండి.',
    'score.rec.insurance.good': 'మీకు మంచి ఇన్సూరెన్స్ కవరేజ్ ఉంది. రక్షణలో ఉండండి!',
    'score.rec.insurance.bad': 'రక్షణ కోసం హెల్త్ మరియు లైఫ్ ఇన్సూరెన్స్ పొందడాన్ని పరిగణించండి.',
    'score.rec.invest.good': 'క్రమం తప్పకుండా పెట్టుబడి పెట్టడం దీర్ఘకాలిక సంపదను నిర్మిస్తుంది. గొప్ప అలవాటు!',
    'score.rec.invest.bad': 'మీ సంపదను పెంచుకోవడానికి SIP లేదా క్రమబద్ధ పెట్టుబడిని ప్రారంభించండి.',
    'score.rec.planning.good': 'బడ్జెట్ మరియు ఎస్టేట్ ప్లాన్ కలిగి ఉండటం గొప్ప క్రమశిక్షణను చూపిస్తుంది!',
    'score.rec.planning.bad': 'నెలవారీ బడ్జెట్‌ను రూపొందించండి మరియు వీలునామా చేయడాన్ని పరిగణించండి.',
    'score.reset': 'రీసెట్',
    'score.yes': 'అవును',
    'score.no': 'కాదు',
    'score.age': 'మీ వయస్సు',
    'score.dependents': 'ఆధారపడేవారి సంఖ్య',
    'score.cityTier': 'నగర రకం',
    'score.tier1': 'మెట్రో',
    'score.tier2': 'అర్బన్',
    'score.tier3': 'రూరల్',
    'score.insuranceNote': 'పరిశ్రమ ప్రమాణాల ఆధారంగా వ్యక్తిగతీకరించిన హెల్త్ ఇన్సూరెన్స్ మరియు టర్మ్ ఇన్సూరెన్స్ సిఫార్సులతో మీ స్కోర్ పొందండి.',

    'ins.perYear': 'సం',
    'ins.howCalculated': 'ఇది ఎలా లెక్కించబడింది',
    'ins.health.title': 'హెల్త్ ఇన్సూరెన్స్ సిఫార్సు',
    'ins.health.subtitle': 'ఫ్యామిలీ ఫ్లోటర్ ప్లాన్ — మీరు, భార్య/భర్త & పిల్లలను భాగస్వామ్య బీమా మొత్తంతో కవర్ చేస్తుంది.',
    'ins.health.recommended': 'సిఫార్సు చేసిన కవర్',
    'ins.health.premium': 'అంచనా వార్షిక ప్రీమియం',
    'ins.health.familySize': 'కుటుంబ పరిమాణం',
    'ins.health.members': 'సభ్యులు కవర్ చేయబడ్డారు',
    'ins.health.coverBreakdown': 'ఫ్యామిలీ ఫ్లోటర్ విభజన',
    'ins.health.totalCover': 'మొత్తం సిఫార్సు కవర్',
    'ins.health.familyDetails': 'కుటుంబ వివరాలు (హెల్త్ ఇన్సూరెన్స్ కోసం)',
    'ins.health.hasSpouse': 'భార్య/భర్తను చేర్చాలా?',
    'ins.health.spouseAge': 'భార్య/భర్త వయస్సు',
    'ins.health.children': 'పిల్లలు',
    'ins.health.parents': 'తల్లిదండ్రులు',
    'ins.health.parentAge': 'పెద్ద తల్లిదండ్రి వయస్సు',
    'ins.health.plan.individual': 'వ్యక్తిగత ప్లాన్',
    'ins.health.plan.familyFloater': 'ఫ్యామిలీ ఫ్లోటర్',
    'ins.health.plan.multiGen': 'మల్టీ-జెన్ ఫ్లోటర్',
    'ins.health.breakdown.self': 'స్వయం (బేస్ కవర్)',
    'ins.health.breakdown.spouse': 'భార్య/భర్త కవర్',
    'ins.health.breakdown.children': 'పిల్లల కవర్',
    'ins.health.breakdown.parents': 'తల్లిదండ్రుల కవర్',
    'ins.health.breakdown.city': 'నగర ఖర్చు సర్దుబాటు',
    'ins.health.breakdown.age': 'వయస్సు రిస్క్ సర్దుబాటు',
    'ins.health.breakdown.inflation': 'వైద్య ద్రవ్యోల్బణం (8% x 5సం)',
    'ins.health.disclaimer': '*ప్రీమియంలు పరిశ్రమ ప్రమాణ రేట్ల ఆధారంగా సూచనాత్మక అంచనాలు. బీమా సంస్థ, వైద్య చరిత్ర, లోడింగ్ ఛార్జీలు ప్రకారం వాస్తవ ప్రీమియంలు మారతాయి. ఖచ్చితమైన కోట్‌ల కోసం సలహాదారుని సంప్రదించండి.',
    'ins.health.reason.floater': 'ఫ్యామిలీ ఫ్లోటర్ విధానం — ఒకే పాలసీ అన్ని కుటుంబ సభ్యులను భాగస్వామ్య బీమా మొత్తంలో కవర్ చేస్తుంది',
    'ins.health.reason.metro': 'మెట్రో నగర గుణకం (1.5x) — టైర్ 1 నగరాల్లో ఎక్కువ వైద్య ఖర్చులు',
    'ins.health.reason.urban': 'అర్బన్ నగర గుణకం (1.2x) — మితమైన వైద్య ఖర్చు సర్దుబాటు',
    'ins.health.reason.age55': '55+ వయస్సు గుణకం (1.4x) — సీనియర్ సభ్యులకు ఎక్కువ ప్రమాదం',
    'ins.health.reason.age45': '45+ వయస్సు గుణకం (1.3x) — జీవనశైలి వ్యాధుల ఎక్కువ ప్రమాదం',
    'ins.health.reason.age35': '35+ వయస్సు గుణకం (1.15x) — నివారణ సంరక్షణ పరిగణన',
    'ins.health.reason.inflation': 'వైద్య ద్రవ్యోల్బణ సర్దుబాటు (5 సంవత్సరాలలో 8% వార్షిక) కవరేజ్‌ను భవిష్యత్తుకు సురక్షితం చేయడానికి',

    'ins.term.title': 'టర్మ్ ఇన్సూరెన్స్ సిఫార్సు',
    'ins.term.subtitle': 'హ్యూమన్ లైఫ్ వాల్యూ (HLV) పద్ధతి ఉపయోగించి లెక్కించబడింది — పరిశ్రమ ప్రమాణ విధానం.',
    'ins.term.recommended': 'సిఫార్సు చేసిన కవర్',
    'ins.term.premium': 'అంచనా వార్షిక ప్రీమియం',
    'ins.term.formula': 'కవరేజ్ విభజన',
    'ins.term.incomeReplace': '10x వార్షిక ఆదాయ భర్తీ',
    'ins.term.debtCover': 'బాకీ ఉన్న అప్పు కవర్',
    'ins.term.childEdu': 'పిల్లల విద్యా నిధి (ఒక్కొక్కరికి ₹25L)',
    'ins.term.totalNeed': 'సిఫార్సు చేసిన కవర్',
    'ins.term.disclaimer': '*టర్మ్ ఇన్సూరెన్స్ ప్రీమియంలు నాన్-స్మోకర్ రేట్ల ఆధారంగా అంచనాలు. వాస్తవ ప్రీమియం ఆరోగ్యం, అలవాట్లు, బీమా సంస్థ మరియు పాలసీ కాలం మీద ఆధారపడి ఉంటుంది.',

    'ins.existing.healthCover': 'మీ ప్రస్తుత హెల్త్ ఇన్సూరెన్స్ సమ్ ఇన్సూర్డ్',
    'ins.existing.healthHint': 'మీ ప్రస్తుత హెల్త్ ఇన్సూరెన్స్ పాలసీ యొక్క మొత్తం సమ్ ఇన్సూర్డ్ నమోదు చేయండి (₹లో)',
    'ins.existing.termCover': 'మీ ప్రస్తుత టర్మ్ ఇన్సూరెన్స్ సమ్ ఇన్సూర్డ్',
    'ins.existing.termHint': 'మీ ప్రస్తుత టర్మ్/లైఫ్ ఇన్సూరెన్స్ పాలసీ యొక్క మొత్తం సమ్ ఇన్సూర్డ్ నమోదు చేయండి (₹లో)',
    'ins.verdict.sufficient': 'మీ కవరేజ్ తగినంతగా ఉంది!',
    'ins.verdict.insufficient': 'మీ కవరేజ్ సరిపోకపోవచ్చు',
    'ins.verdict.yourCover': 'మీ ప్రస్తుత కవర్',
    'ins.verdict.recommended': 'సిఫార్సు చేసిన కవర్',
    'ins.verdict.gap': 'కవరేజ్ గ్యాప్',
    'ins.verdict.surplus': 'కవరేజ్ మిగులు',

    'ins.term.reason.income': 'కుటుంబ జీవనశైలిని రక్షించడానికి 10x వార్షిక ఆదాయ భర్తీ',
    'ins.term.reason.debt': 'అన్ని బాధ్యతలను తీర్చడానికి బాకీ ఉన్న అప్పు కవరేజ్',
    'ins.term.reason.dependents': 'ఆధారపడే వ్యక్తికి ₹25L పిల్లల విద్యా నిధి',
    'ins.term.reason.hlv': 'హ్యూమన్ లైఫ్ వాల్యూ (HLV) పద్ధతి ఉపయోగించబడింది — పరిశ్రమ ప్రమాణం',
    'ins.term.reason.minimum': 'కనీస సిఫార్సు టర్మ్ కవర్ ₹50L',

    'ins.parents.title': 'తల్లిదండ్రుల హెల్త్ ఇన్సూరెన్స్',
    'ins.parents.subtitle': 'తల్లిదండ్రులకు ప్రత్యేక పాలసీ సిఫార్సు — వయస్సు సంబంధిత ప్రమాదం కారణంగా ప్రీమియంలు ఎక్కువ.',
    'ins.parents.planType': 'సీనియర్ సిటిజన్ ప్లాన్',
    'ins.parents.breakdown': 'తల్లిదండ్రుల కవర్ విభజన',
    'ins.parents.disclaimer': 'తల్లిదండ్రులకు ప్రత్యేక హెల్త్ ఇన్సూరెన్స్ పాలసీ తీసుకోవడం మంచిది. వారి ఎక్కువ వయస్సు కారణంగా, వారిని ఫ్యామిలీ ఫ్లోటర్‌లో చేర్చడం మొత్తం ప్రీమియంను గణనీయంగా పెంచుతుంది మరియు యువ సభ్యులకు క్లెయిమ్ ప్రయోజనాలను తగ్గించవచ్చు. తల్లిదండ్రులకు ప్రత్యేక సీనియర్ సిటిజన్ లేదా వ్యక్తిగత ప్లాన్ మెరుగైన కవరేజ్ మరియు అనుకూల నిబంధనలను నిర్ధారిస్తుంది.',

    'nav.info': 'ది టీ',

    'info.title': 'ఇన్సూరెన్స్ పై ది టీ',
    'info.desc': 'IRDAI నుండి నిజమైన డేటా మరియు వాస్తవ పరిస్థితులతో హెల్త్ మరియు టర్మ్ ఇన్సూరెన్స్ ఎందుకు అవసరమో తెలుసుకోండి.',
    'info.whatIs': 'ఇది ఏమిటి?',
    'info.keyFacts': 'ముఖ్యమైన వాస్తవాలు & సంఖ్యలు',
    'info.realLifeExamples': 'నిజ జీవిత పరిస్థితులు',
    'info.cta': 'మీ ఆర్థిక ఆరోగ్యాన్ని తనిఖీ చేసుకొని వ్యక్తిగతీకరించిన ఇన్సూరెన్స్ సిఫార్సులు పొందడానికి సిద్ధంగా ఉన్నారా?',
    'info.ctaButton': 'మీ ఫిన్ స్కోర్ తనిఖీ చేయండి',

    'info.health.title': 'హెల్త్ ఇన్సూరెన్స్',
    'info.health.subtitle': 'వైద్య అత్యవసర పరిస్థితులకు మీ మొదటి రక్షణ',
    'info.health.what': 'హెల్త్ ఇన్సూరెన్స్ ఆసుపత్రి చేరిక, శస్త్రచికిత్స మరియు వైద్య చికిత్స ఖర్చులను కవర్ చేస్తుంది. భారతదేశంలో వైద్య ద్రవ్యోల్బణం సంవత్సరానికి 14% — సాధారణ ద్రవ్యోల్బణం కంటే రెట్టింపు. ఈరోజు ₹5 లక్షలు ఖర్చయ్యే హార్ట్ బైపాస్ 5 సంవత్సరాల్లో ₹10 లక్షలు అవుతుంది. ఫ్యామిలీ ఫ్లోటర్ ప్లాన్ మీ మొత్తం కుటుంబాన్ని ఒకే పాలసీలో కవర్ చేస్తుంది.',
    'info.health.fact1': 'భారతదేశంలో వైద్య ద్రవ్యోల్బణం సంవత్సరానికి 14% — ఆసియాలో అత్యధికం. ఆసుపత్రి బిల్లులు ప్రతి 5 సంవత్సరాలకు రెట్టింపు అవుతాయి.',
    'info.health.fact2': 'మెట్రో నగరంలో హార్ట్ సర్జరీ సగటు ఖర్చు: ₹3.5L నుండి ₹8L. క్యాన్సర్ చికిత్స: ₹10L నుండి ₹30L+.',
    'info.health.fact3': 'కేవలం 25% భారతీయులకు ఏదైనా రకమైన హెల్త్ ఇన్సూరెన్స్ ఉంది. మిగిలిన 75% మంది పొదుపు నుండి చెల్లిస్తారు లేదా అప్పు చేస్తారు.',
    'info.health.fact4': 'భారతదేశంలో 62% వైద్య ఖర్చులు జేబు నుండి చెల్లించబడతాయి — ప్రపంచంలో 3వ అత్యధికం (WHO డేటా).',
    'info.health.fact5': 'హెల్త్ ఇన్సూరెన్స్ పరిశ్రమ క్లెయిమ్స్ రేషియో: 55-65%, అంటే ప్రతి ₹100 వసూలు చేసిన దాంట్లో ₹55-65 క్లెయిమ్స్‌లో తిరిగి చెల్లించబడుతుంది.',
    'info.health.floaterTitle': 'ఫ్యామిలీ ఫ్లోటర్ ఎలా పనిచేస్తుంది',
    'info.health.floaterDesc': 'ఫ్యామిలీ ఫ్లోటర్ ప్లాన్‌లో, మొత్తం కుటుంబం ఒక ఉమ్మడి బీమా మొత్తాన్ని భాగస్వామ్యం చేస్తుంది. ఉదాహరణకు, మీరు ₹10 లక్షల ఫ్యామిలీ ఫ్లోటర్ కొంటే, ఏ కుటుంబ సభ్యుడైనా ₹10 లక్షల వరకు క్లెయిమ్ చేయవచ్చు. ప్రీమియం పెద్ద సభ్యుని వయస్సు ఆధారంగా లెక్కించబడుతుంది. ఇది ప్రతి సభ్యునికి వ్యక్తిగత పాలసీలు కొనడం కంటే చాలా చౌకగా ఉంటుంది.',

    'info.health.scenario1.title': 'రాహుల్, 32 — అపెండిసైటిస్ సర్జరీ',
    'info.health.scenario1.desc': 'రాహుల్‌కు అత్యవసర అపెండిసైటిస్ సర్జరీ జరిగింది. ఆసుపత్రి బిల్లు: ₹2.8 లక్షలు. ఇన్సూరెన్స్ లేకుండా, అతని 6 నెలల అత్యవసర నిధి ఖాళీ అయ్యేది. అతని ₹5L ఫ్లోటర్‌తో, మొత్తం బిల్లు క్యాష్‌లెస్‌గా సెటిల్ అయింది.',
    'info.health.scenario2.title': 'ప్రియ, 45 — తల్లి మోకాలి మార్పిడి',
    'info.health.scenario2.desc': 'ప్రియ తల్లికి 68 ఏళ్ల వయసులో రెండు మోకాళ్ల మార్పిడి అవసరమైంది. హైదరాబాద్‌లో మొత్తం ఖర్చు: ₹6.5 లక్షలు. ప్రియ తన తల్లిదండ్రులను ₹15L మల్టీ-జెన్ ఫ్లోటర్‌కు జోడించడం వల్ల, ₹5.8L ఇన్సూరెన్స్ ద్వారా కవర్ అయింది.',
    'info.health.scenario3.title': 'అరుణ్, 28 — డెంగ్యూ ఆసుపత్రి చేరిక',
    'info.health.scenario3.desc': 'అరుణ్ తీవ్రమైన డెంగ్యూతో 8 రోజులు ఆసుపత్రిలో చేరాడు. ICU ఛార్జీలు మాత్రమే ₹1.2 లక్షలు. అతని యజమాని అందించిన ₹3L గ్రూప్ కవర్ మొత్తం బిల్లును భరించింది.',

    'info.term.title': 'టర్మ్ ఇన్సూరెన్స్',
    'info.term.subtitle': 'అత్యల్ప ఖర్చుతో స్వచ్ఛమైన జీవిత రక్షణ — మీ కుటుంబ ఆర్థిక భద్రత కోసం',
    'info.term.what': 'టర్మ్ ఇన్సూరెన్స్ అనేది పాలసీ కాలంలో మీకు ఏదైనా జరిగితే మీ కుటుంబానికి ఒకేసారి మొత్తం చెల్లించే స్వచ్ఛమైన రక్షణ ప్లాన్. ఎండోమెంట్ లేదా ULIP ప్లాన్‌ల కంటే భిన్నంగా, ఇందులో పొదుపు లేదా పెట్టుబడి భాగం లేదు — ఇది ప్రీమియంను చాలా తక్కువగా ఉంచుతుంది. 30 ఏళ్ల వ్యక్తి సంవత్సరానికి ₹10,000తో ₹1 కోటి కవర్ పొందవచ్చు.',
    'info.term.fact1': 'కేవలం 3.2% భారతీయులకు తగినంత లైఫ్ ఇన్సూరెన్స్ కవరేజ్ ఉంది (IRDAI వార్షిక నివేదిక 2023-24).',
    'info.term.fact2': 'సగటు భారతీయ లైఫ్ ఇన్సూరెన్స్ కవర్: ₹3-5 లక్షలు. సిఫార్సు: వార్షిక ఆదాయం 10-15 రెట్లు (కనీసం ₹50 లక్షలు).',
    'info.term.fact3': 'టర్మ్ ఇన్సూరెన్స్ అదే కవర్ మొత్తానికి ఎండోమెంట్ ప్లాన్‌ల కంటే 10-15 రెట్లు చౌక.',
    'info.term.fact4': 'టాప్ టర్మ్ బీమా సంస్థల క్లెయిమ్ సెటిల్మెంట్ రేషియో: 97-99%. దాదాపు ప్రతి నిజమైన క్లెయిమ్ చెల్లించబడుతుంది.',
    'info.term.fact5': '25 ఏళ్ల నుండి 35 ఏళ్లకు కొనుగోలు ఆలస్యం చేస్తే అదే కవర్‌కు మీ ప్రీమియం 60-80% పెరుగుతుంది.',
    'info.term.hlvTitle': 'హ్యూమన్ లైఫ్ వాల్యూ (HLV) పద్ధతి',
    'info.term.hlvDesc': 'HLV పద్ధతి మీరు ఇకపై లేకపోతే మీ కుటుంబానికి ఎంత అవసరమో లెక్కిస్తుంది. ఇది పరిగణిస్తుంది: మీ వార్షిక ఆదాయం x రిటైర్మెంట్ వరకు సంవత్సరాలు, బాకీ ఉన్న అప్పులు (హోమ్ లోన్, కార్ లోన్), మరియు పిల్లల విద్యా ఖర్చులు (ఉన్నత విద్యకు ఒక్కొక్క పిల్లవాడికి ₹20-30 లక్షలు). చాలా మంది ఆర్థిక ప్రణాళికదారులు కనీసం మీ వార్షిక ఆదాయం 10 రెట్లు సిఫార్సు చేస్తారు.',

    'info.term.scenario1.title': 'సురేష్, 35 — హోమ్ లోన్ రక్షణ',
    'info.term.scenario1.desc': 'సురేష్ సంవత్సరానికి ₹8L సంపాదిస్తాడు మరియు 20 సంవత్సరాలు మిగిలి ఉన్న ₹40L హోమ్ లోన్ ఉంది. టర్మ్ ఇన్సూరెన్స్ లేకుండా, ఏదైనా జరిగితే, అతని భార్య ₹3L జీతంతో లోన్ తిరిగి చెల్లించాల్సి ఉంటుంది. ₹1 Cr టర్మ్ ప్లాన్‌తో (ప్రీమియం: ₹14,000/సం), లోన్ క్లియర్ అవుతుంది.',
    'info.term.scenario2.title': 'మీనా, 30 — ఏకైక ఆదాయ కుటుంబం',
    'info.term.scenario2.desc': 'మీనా 3 మరియు 5 ఏళ్ల ఇద్దరు పిల్లలతో ఏకైక సంపాదనాపరురాలు. వార్షిక ఆదాయం: ₹12L. ₹2 Cr టర్మ్ ప్లాన్ సంవత్సరానికి కేవలం ₹16,000 ఖర్చవుతుంది మరియు ఆమె పిల్లల భవిష్యత్తును సురక్షితం చేస్తుంది.',
    'info.term.scenario3.title': 'విక్రమ్, 42 — ఆలస్యంగా కొనుగోలు చేసినందుకు ఎక్కువ ఖర్చు',
    'info.term.scenario3.desc': 'విక్రమ్ టర్మ్ ఇన్సూరెన్స్ కొనుగోలు ఆలస్యం చేశాడు. 42 ఏళ్లకు, అతని ₹1 Cr టర్మ్ ప్లాన్ సంవత్సరానికి ₹22,000 ఖర్చవుతుంది. 30 ఏళ్లకు కొనుగోలు చేసి ఉంటే, సంవత్సరానికి ₹10,000 మాత్రమే అయ్యేది. పాఠం: టర్మ్ ఇన్సూరెన్స్ వీలైనంత త్వరగా కొనుగోలు చేయండి.',

    'info.irdai.title': 'IRDAI & భారత ఇన్సూరెన్స్ పరిశ్రమ',
    'info.irdai.about': 'భారత ఇన్సూరెన్స్ నియంత్రణ మరియు అభివృద్ధి ప్రాధికార సంస్థ (IRDAI) భారతదేశంలోని అన్ని ఇన్సూరెన్స్ కంపెనీలను నియంత్రిస్తుంది. ముఖ్యమైన నియంత్రణ వాస్తవాలు:',
    'info.irdai.point1': 'IRDAI వినియోగదారుల రక్షణ కోసం అన్ని బీమా సంస్థలకు కనీస క్లెయిమ్ సెటిల్మెంట్ రేషియోను నిర్దేశిస్తుంది.',
    'info.irdai.point2': 'భారతదేశంలో హెల్త్ ఇన్సూరెన్స్ పాలసీలకు ప్రామాణిక 30-రోజుల వేచి ఉండే కాలం మరియు ముందుగా ఉన్న వ్యాధులకు 2-4 సంవత్సరాల వేచి ఉంటుంది.',
    'info.irdai.point3': 'టర్మ్ ఇన్సూరెన్స్ ప్రీమియంలు నియంత్రించబడతాయి — బీమా సంస్థలు నిజమైన దరఖాస్తుదారులకు అధిక ప్రీమియంలు వసూలు చేయడం సాధ్యం కాదు.',
    'info.irdai.point4': 'పన్ను ప్రయోజనాలు: హెల్త్ ఇన్సూరెన్స్ ప్రీమియంలు సెక్షన్ 80D కింద (సంవత్సరానికి ₹75,000 వరకు) తగ్గింపుకు అర్హత పొందుతాయి. టర్మ్ ఇన్సూరెన్స్ ప్రీమియంలు సెక్షన్ 80C కింద (₹1.5L వరకు) అర్హత పొందుతాయి.',

    'info.irdai.metric1.value': '4%',
    'info.irdai.metric1.label': 'ఇన్సూరెన్స్ వ్యాప్తి (భారతదేశం)',
    'info.irdai.metric2.value': '97%',
    'info.irdai.metric2.label': 'టర్మ్ క్లెయిమ్ సెటిల్మెంట్',
    'info.irdai.metric3.value': '14%',
    'info.irdai.metric3.label': 'వైద్య ద్రవ్యోల్బణ రేటు',
    'info.irdai.metric4.value': '75%',
    'info.irdai.metric4.label': 'హెల్త్ కవర్ లేని జనాభా',
    'info.irdai.metric5.value': '₹6,600',
    'info.irdai.metric5.label': 'తలసరి ప్రీమియం (₹)',
    'info.irdai.metric6.value': '58+',
    'info.irdai.metric6.label': 'ఇన్సూరెన్స్ కంపెనీలు',

    'contact.title': 'మమ్మల్ని సంప్రదించండి',
    'contact.desc': 'మీ ఆర్థిక భవిష్యత్తును సురక్షితం చేసుకోవడానికి సిద్ధంగా ఉన్నారా? మా ధృవీకరించబడిన నిపుణులతో ఈరోజే ప్రొఫెషనల్ కన్సల్టేషన్‌ను బుక్ చేయండి.',
    'contact.phone': 'ఫోన్',
    'contact.email': 'ఈమెయిల్',
    'contact.office': 'ఆఫీస్',
    'contact.reply': 'మేము 24 గంటల్లో ప్రత్యుత్తరం ఇస్తాము',
    'contact.form.title': 'మమ్మల్ని సంప్రదించండి',
    'contact.form.desc': 'వాట్సాప్ లేదా ఫోన్ ద్వారా మా నిపుణులతో కనెక్ట్ అవ్వడానికి క్రింద క్లిక్ చేయండి.',
    'contact.whatsapp': 'వాట్సాప్‌లో చాట్ చేయండి',
    'contact.call': 'ఇప్పుడే మాకు కాల్ చేయండి',
  }
};

export const useLanguage = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language;
        return translations[lang][key as keyof typeof translations['en']] || key;
      },
    }),
    {
      name: 'hanvitt-language-storage',
    }
  )
);
